package vo;
// Generated 06/09/2012 17:52:15 by Hibernate Tools 3.2.1.GA

import java.util.Date;


/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {

     private Integer codigo;
     private String nome;
     private String sobrenome;
     private String  telefone;
     private String telefone2;
     private TipoPessoa tipo;
     private String cpf;
     private String rg;
     private String email;
     private String senha;
     private Date nascimento;
     
     public Integer getCodigo() {
          return codigo;
     }

     public void setCodigo(Integer codigo) {
          this.codigo = codigo;
     }

     public String getNome() {
          return nome;
     }

     public void setNome(String nome) {
          this.nome = nome;
     }

     public String getSobrenome() {
          return sobrenome;
     }

     public void setSobrenome(String sobrenome) {
          this.sobrenome = sobrenome;
     }

     public String getTelefone() {
          return telefone;
     }

     public void setTelefone(String telefone) {
          this.telefone = telefone;
     }

     public TipoPessoa getTipo() {
          return tipo;
     }

     public void setTipo(TipoPessoa tipo) {
          this.tipo = tipo;
     }

     public String getCpf() {
          return cpf;
     }

     public void setCpf(String cpf) {
          this.cpf = cpf;
     }

     public String getEmail() {
          return email;
     }

     public void setEmail(String email) {
          this.email = email;
     }

     public String getSenha() {
          return senha;
     }

     public void setSenha(String senha) {
          this.senha = senha;
     }

     public String getTelefone2() {
          return telefone2;
     }

     public void setTelefone2(String telefone2) {
          this.telefone2 = telefone2;
     }

     public String getRg() {
          return rg;
     }

     public void setRg(String rg) {
          this.rg = rg;
     }

     public Date getNascimento() {
          return nascimento;
     }

     public void setNascimento(Date nascimento) {
          this.nascimento = nascimento;
     }



}


