package vo;
// Generated 06/09/2012 17:52:15 by Hibernate Tools 3.2.1.GA


/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {

     private Integer codigo;
     private String usuario;
     private String senha;
     private String primeironome;
     private String ultimonome;
     private int    estado;
     private String email;
     private String importsenha;
     private String token;
     private String usertoken;
     private String userrole;
     private int userapi;
     private int codvendedor;
     
    public Usuario() {
    }

     public Integer getCodigo() {
          return codigo;
     }

     public void setCodigo(Integer codigo) {
          this.codigo = codigo;
     }

     public String getUsuario() {
          return usuario;
     }

     public void setUsuario(String usuario) {
          this.usuario = usuario;
     }

     public String getSenha() {
          return senha;
     }

     public void setSenha(String senha) {
          this.senha = senha;
     }

     public String getPrimeironome() {
          return primeironome;
     }

     public void setPrimeironome(String primeironome) {
          this.primeironome = primeironome;
     }

     public String getUltimonome() {
          return ultimonome;
     }

     public void setUltimonome(String ultimonome) {
          this.ultimonome = ultimonome;
     }

     public int getEstado() {
          return estado;
     }

     public void setEstado(int estado) {
          this.estado = estado;
     }

     public String getEmail() {
          return email;
     }

     public void setEmail(String email) {
          this.email = email;
     }

     public String getImportsenha() {
          return importsenha;
     }

     public void setImportsenha(String importsenha) {
          this.importsenha = importsenha;
     }

     public String getToken() {
          return token;
     }

     public void setToken(String token) {
          this.token = token;
     }

     public String getUsertoken() {
          return usertoken;
     }

     public void setUsertoken(String usertoken) {
          this.usertoken = usertoken;
     }

     public int getUserapi() {
          return userapi;
     }

     public void setUserapi(int userapi) {
          this.userapi = userapi;
     }

     public String getUserrole() {
          return userrole;
     }

     public void setUserrole(String userrole) {
          this.userrole = userrole;
     }

     public int getCodvendedor() {
          return codvendedor;
     }

     public void setCodvendedor(int codvendedor) {
          this.codvendedor = codvendedor;
     }

}


