package vo;
// Generated 06/09/2012 17:52:15 by Hibernate Tools 3.2.1.GA


/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {

     private Integer codigo;
     private String nome;
     private String telefone;
     private String email;
     private String endereço;
     private String cidade;
     private String estado;
     private String cep;
     private String pais;
     private String descricao;
     private double comissao;
     
    public Vendedor() {
    }

     public Integer getCodigo() {
          return codigo;
     }

     public void setCodigo(Integer codigo) {
          this.codigo = codigo;
     }

     public String getNome() {
          return nome;
     }

     public void setNome(String nome) {
          this.nome = nome;
     }

     public String getTelefone() {
          return telefone;
     }

     public void setTelefone(String telefone) {
          this.telefone = telefone;
     }

     public String getEmail() {
          return email;
     }

     public void setEmail(String email) {
          this.email = email;
     }

     public String getEndereço() {
          return endereço;
     }

     public void setEndereço(String endereço) {
          this.endereço = endereço;
     }

     public String getCidade() {
          return cidade;
     }

     public void setCidade(String cidade) {
          this.cidade = cidade;
     }

     public String getEstado() {
          return estado;
     }

     public void setEstado(String estado) {
          this.estado = estado;
     }

     public String getCep() {
          return cep;
     }

     public void setCep(String cep) {
          this.cep = cep;
     }

     public String getPais() {
          return pais;
     }

     public void setPais(String pais) {
          this.pais = pais;
     }

     public String getDescricao() {
          return descricao;
     }

     public void setDescricao(String descricao) {
          this.descricao = descricao;
     }

     public double getComissao() {
          return comissao;
     }

     public void setComissao(double comissao) {
          this.comissao = comissao;
     }

}


