/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.CategoriaProdutoRN;
import negocio.ComprarRN;
import negocio.ItemCompraRN;
import negocio.PessoaRN;
import negocio.ProdutoRN;
import persistencia.Conexao;
import recursos.utilitarios.Mascara;
import recursos.utilitarios.TableModel;
import vo.CategoriaProduto;
import vo.Comprar;
import vo.ItemCompra;
import vo.Pessoa;
import vo.Produto;

/**
 *
 * @author ThyagoHenrique
 */
public class JFComprar extends javax.swing.JFrame {
     
     Mascara                  mas                 = new Mascara();
     String                   titulo_icompra[]    = new String[]{"Produto", "Preço", "Quantidade"};
     TableModel               tm_icompra          = new TableModel(titulo_icompra, 1, titulo_icompra.length);  
     String                   titulo[]            = new String[]{"Código", "Data", "Fornecedor", "Valor"};
     TableModel               tm                  = new TableModel(titulo, 1, titulo.length);     
     List<Produto>            obj_produto         = new ArrayList();
     List<Comprar>            obj                 = new ArrayList();
     Comprar                  comprar             = new Comprar();
     ComprarRN                crn                 = new ComprarRN();
     List<CategoriaProduto>   obj_categoria       = new ArrayList();
     CategoriaProdutoRN       cprn                = new CategoriaProdutoRN();
     CategoriaProduto         categoria           = new CategoriaProduto();
     ProdutoRN                prn                 = new ProdutoRN();
     List<Pessoa>             obj_pessoa          = new ArrayList();
     PessoaRN                 pern                = new PessoaRN();
     Pessoa                   pessoa              = new Pessoa();
     Produto                  produto             = new Produto();
     ItemCompra               icompra             = new ItemCompra();
     ItemCompraRN             icrn                = new ItemCompraRN();
     List<ItemCompra>         obj_icompra         = new ArrayList();
     int                      qtd_item            = 1;
     Conexao                  cx;
     private double           total_compra;
     private boolean          novofornecedor      = false;
     /**
      * Creates new form JFComprar
      */
     public JFComprar() {
          initComponents();
     }

     public JFComprar(Conexao cx) {
          initComponents();
          this.cx = cx;
          tabela.setModel(tm);
          dcdtcompra.setDate(new Date());
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTabbedPane1 = new javax.swing.JTabbedPane();
          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          tpreco = new javax.swing.JTextField();
          tquantidade = new javax.swing.JTextField();
          botao_sair = new javax.swing.JButton();
          botao_excluir = new javax.swing.JButton();
          botao_inserir = new javax.swing.JButton();
          jLabel7 = new javax.swing.JLabel();
          cfornecedor = new javax.swing.JComboBox();
          jLabel8 = new javax.swing.JLabel();
          tcodigobarra = new javax.swing.JTextField();
          lmensagem = new javax.swing.JLabel();
          tnome_produto = new javax.swing.JTextField();
          jLabel5 = new javax.swing.JLabel();
          dcdtcompra = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
          dcdtvencimento = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
          jLabel9 = new javax.swing.JLabel();
          jLabel10 = new javax.swing.JLabel();
          tparcela = new javax.swing.JTextField();
          badicionar_fornecedor = new javax.swing.JButton();
          badicionar_produto = new javax.swing.JButton();
          jPanel2 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          tabela_icompra = new javax.swing.JTable();
          jLabel4 = new javax.swing.JLabel();
          ltotalgasto = new javax.swing.JLabel();
          bexcluir = new javax.swing.JButton();
          jPanel3 = new javax.swing.JPanel();
          botao_procurar = new javax.swing.JButton();
          tnomeproc = new javax.swing.JTextField();
          jScrollPane2 = new javax.swing.JScrollPane();
          tabela = new javax.swing.JTable();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Gerencia Compras efetuadas pela loja");
          addWindowListener(new java.awt.event.WindowAdapter() {
               public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
               }
          });

          jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusGained(java.awt.event.FocusEvent evt) {
                    jTabbedPane1FocusGained(evt);
               }
          });

          jLabel1.setText("Produto");

          jLabel2.setText("Preço");

          jLabel3.setText("Quantidade");

          tpreco.setToolTipText("Preço de custo");

          tquantidade.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    tquantidadeKeyTyped(evt);
               }
          });

          botao_sair.setText("Sair");
          botao_sair.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botao_sairActionPerformed(evt);
               }
          });

          botao_excluir.setText("Excluir");
          botao_excluir.setToolTipText("Excluir compra");
          botao_excluir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botao_excluirActionPerformed(evt);
               }
          });

          botao_inserir.setText("Finalizar");
          botao_inserir.setToolTipText("Finalizar Compra");
          botao_inserir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botao_inserirActionPerformed(evt);
               }
          });

          jLabel7.setText("Fornecedor");

          cfornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cfornecedorMouseClicked(evt);
               }
          });
          cfornecedor.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cfornecedorActionPerformed(evt);
               }
          });

          jLabel8.setText("Cód. Barra");

          tcodigobarra.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyReleased(java.awt.event.KeyEvent evt) {
                    tcodigobarraKeyReleased(evt);
               }
          });

          lmensagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
          lmensagem.setText("Mensagem do sistema");

          tnome_produto.setEnabled(false);

          jLabel5.setText("Data");

          dcdtvencimento.setToolTipText("Colocado o dia de hoje por padrão");

          jLabel9.setText("Vencimento");

          jLabel10.setText("Parcelas");

          tparcela.setToolTipText("Se pagou em mais de uma parcela");
          tparcela.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusLost(java.awt.event.FocusEvent evt) {
                    tparcelaFocusLost(evt);
               }
          });

          badicionar_fornecedor.setText("+");
          badicionar_fornecedor.setToolTipText("Adicionar novos fornecedores");
          badicionar_fornecedor.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    badicionar_fornecedorActionPerformed(evt);
               }
          });

          badicionar_produto.setText("+");
          badicionar_produto.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    badicionar_produtoActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel7)
                                   .addComponent(jLabel8))
                              .addGap(18, 18, 18)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(tcodigobarra)
                                             .addComponent(cfornecedor, 0, 307, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(badicionar_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                   .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(botao_inserir)
                                        .addGap(18, 18, 18)
                                        .addComponent(botao_excluir)
                                        .addGap(18, 18, 18)
                                        .addComponent(botao_sair)
                                        .addGap(10, 10, 10)))
                              .addGap(21, 21, 21))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addComponent(lmensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addContainerGap())
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel2)
                                   .addComponent(jLabel1)
                                   .addComponent(jLabel5)
                                   .addComponent(jLabel9))
                              .addGap(18, 18, 18)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(dcdtvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                             .addComponent(tnome_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGroup(jPanel1Layout.createSequentialGroup()
                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addComponent(tpreco)
                                                       .addComponent(dcdtcompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                  .addGap(18, 18, 18)
                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                       .addComponent(jLabel3)
                                                       .addComponent(jLabel10))
                                                  .addGap(18, 18, 18)
                                                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                       .addComponent(tquantidade)
                                                       .addComponent(tparcela, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addComponent(badicionar_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addGap(0, 0, Short.MAX_VALUE))))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel8)
                         .addComponent(tcodigobarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel7)
                         .addComponent(cfornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(badicionar_fornecedor))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(tnome_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel1)
                                   .addComponent(badicionar_produto))
                              .addGap(18, 18, 18)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(jLabel3)
                                   .addComponent(tpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(tquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel2))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(dcdtcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tparcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(dcdtvencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                              .addComponent(jLabel5)
                              .addGap(18, 18, 18)
                              .addComponent(jLabel9)))
                    .addGap(27, 27, 27)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(botao_sair)
                         .addComponent(botao_excluir)
                         .addComponent(botao_inserir))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                    .addComponent(lmensagem)
                    .addGap(27, 27, 27))
          );

          jTabbedPane1.addTab("Inserir Compra", jPanel1);

          tabela_icompra.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
               },
               new String [] {
                    "Produto", "Preço", "Quantidade"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }
          });
          tabela_icompra.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabela_icompraMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tabela_icompra);

          jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          jLabel4.setText("Valor Total:");

          ltotalgasto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
          ltotalgasto.setText("0,00");

          bexcluir.setText("Excluir Item");
          bexcluir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluirActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(88, 88, 88)
                              .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(ltotalgasto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addGap(127, 127, 127)
                              .addComponent(bexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(127, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                         .addContainerGap()))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bexcluir)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(ltotalgasto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                         .addGap(50, 50, 50)
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(48, Short.MAX_VALUE)))
          );

          jTabbedPane1.addTab("Itens Compra", jPanel2);

          botao_procurar.setText("Procurar");
          botao_procurar.setToolTipText("Digite o nome do cliente para se procurar");
          botao_procurar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botao_procurarActionPerformed(evt);
               }
          });

          tabela.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Código", "Data", "Fornecedor", "Valor"
               }
          ));
          tabela.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelaMouseClicked(evt);
               }
          });
          jScrollPane2.setViewportView(tabela);

          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
          jPanel3.setLayout(jPanel3Layout);
          jPanel3Layout.setHorizontalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tnomeproc, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(botao_procurar)
                    .addContainerGap())
               .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                         .addContainerGap()
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                         .addContainerGap()))
          );
          jPanel3Layout.setVerticalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(botao_procurar)
                         .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(316, Short.MAX_VALUE))
               .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                         .addContainerGap(47, Short.MAX_VALUE)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(21, Short.MAX_VALUE)))
          );

          jTabbedPane1.addTab("Procura Compra", jPanel3);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane1)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane1)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void tquantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tquantidadeKeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_tquantidadeKeyTyped

     private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
          this.dispose();
     }//GEN-LAST:event_botao_sairActionPerformed

     private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
          String msg      = "";
          int    response = JOptionPane.showConfirmDialog(null, "Tem certeza disso,\n"
               + "Você quer excluir?", "Confirmação de excluir:",
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if (response == JOptionPane.YES_OPTION) {
               if(comprar != null && comprar.getCodigo() != null){
                    msg = crn.excluirComprar(cx, comprar);
               }else{
                    msg = "Procure antes uma compra";
               }
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.remove(comprar);
               listar();
               JOptionPane.showMessageDialog(null, "Excluido com sucesso");
          }
     }//GEN-LAST:event_botao_excluirActionPerformed

     private void botao_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_inserirActionPerformed
          String msg = "";
          try{
               comprar   = new Comprar();
               setaComprar();
               if(comprar.getParcela() > 1){
                    int dia        = comprar.getVencimento().getDay();
                    int mes        = comprar.getVencimento().getMonth();
                    int ano        = comprar.getVencimento().getYear() + 1900;
                    int parcela    = comprar.getParcela();
                    for(int i = 0; i < comprar.getParcela(); i++){
                         comprar.setVencimento(mas.convertePDate(dia + "/" + mes + "/" + ano));
                         comprar.setParcela(parcela);
                         mes++;
                         parcela--;
                         if(mes == 12){
                              mes = 1;
                              ano++;
                         }
                         msg = crn.inserirComprar(cx, comprar);
                         if(msg != null && !msg.isEmpty()){
                              break;
                         }
                    }
               }else{
                    msg = crn.inserirComprar(cx, comprar);
               }
          }catch(Exception ex){
               msg = "Erro ocasionado por:\n" + ex;
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               if(obj_icompra != null && !obj_icompra.isEmpty()){
                    for (ItemCompra ic : obj_icompra) {
                         ic.setComprar(comprar);
                         msg = icrn.inserirItemCompra(cx, ic);
                         if(msg != null && !msg.isEmpty()){
                              break;
                         }
                    }

               }
               JOptionPane.showMessageDialog(null, "Inserido com sucesso");
          }
     }//GEN-LAST:event_botao_inserirActionPerformed

     private void cfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfornecedorActionPerformed
          if(obj_pessoa != null && !obj_pessoa.isEmpty() && (cfornecedor.getSelectedIndex() != -1)){
               pessoa = obj_pessoa.get(cfornecedor.getSelectedIndex());
          }
     }//GEN-LAST:event_cfornecedorActionPerformed

     private void tcodigobarraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcodigobarraKeyReleased
          try{
               produto = prn.procuraCodigoBarra(cx, tcodigobarra.getText());
               if(produto != null && produto.getCategoria() != null && produto.getNome() != null){
                    setaTelaProduto();
                    icompra = new ItemCompra();
                    if(tquantidade.getText() == null || tquantidade.getText().isEmpty() || "0".equals(tquantidade.getText())){
                         tquantidade.setText("1");
                    }
                    icompra.setQuantidade(Integer.valueOf(tquantidade.getText()));
                    icompra.setProduto(produto);
                    produto.setPreconormal(produto.getPrecovenda());
                    double soma  = Mascara.formatToDouble(ltotalgasto.getText());
                    if(String.valueOf(produto.getPreconormal()) != null && produto.getPreconormal() != 0){
                         total_compra = (soma + produto.getPreconormal());
                    }
                    icompra.setComprar(comprar);
                    icompra.setValor(produto.getPrecovenda());

                    obj_icompra.add(icompra);
                    listar_icompra();
                    ltotalgasto.setText(Mascara.formatMoeda(total_compra));
                    limpar();
                    lmensagem.setText("Item de venda " + qtd_item + " inserido com sucesso");
                    qtd_item++;//qtd de itens de venda para apresentar
               }
          }catch(Exception ex){
               JOptionPane.showMessageDialog(null,"Erro causado por\n" + ex);
               lmensagem.setText("Problema ao inserir item de venda");
          }
     }//GEN-LAST:event_tcodigobarraKeyReleased

     private void tparcelaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tparcelaFocusLost
          int parc = Integer.valueOf(tparcela.getText());
          if(parc > 1){
               int       mes        = dcdtvencimento.getDate().getMonth() + 1;
               int       ano        = 1900 + dcdtvencimento.getDate().getYear();
               String    vencimento = dcdtvencimento.getDate().getDay() +  "-" + mes + "-"  + ano;
               dcdtvencimento.setDate(mas.convertePDate(vencimento));
          }
     }//GEN-LAST:event_tparcelaFocusLost

     private void tabela_icompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_icompraMouseClicked
          if(obj_icompra != null && !obj_icompra.isEmpty()){
               icompra = obj_icompra.get(tabela_icompra.getSelectedRow());
          }
     }//GEN-LAST:event_tabela_icompraMouseClicked

     private void bexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluirActionPerformed
          String msg = "";
          if(icompra != null &&
               icompra.getComprar() != null &&
               icompra.getComprar().getCodigo() != null &&
               icompra.getProduto() != null &&
               icompra.getProduto().getCodigo() != null){
               msg = icrn.excluirItemCompra(cx, icompra);
          }else{
               if(icompra != null &&
                    (icompra.getComprar() == null || icompra.getCodigo() == null) &&
                    icompra.getProduto() != null &&
                    icompra.getProduto().getCodigo() != null){
                    obj_icompra.remove(icompra);
                    listar_icompra();
               }else{
                    msg = "Selecione um item antes da tabela";
               }
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               JOptionPane.showMessageDialog(null, "Excluido com sucesso");
          }
     }//GEN-LAST:event_bexcluirActionPerformed

     private void botao_procurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_procurarActionPerformed
          obj = crn.procuraNomeParcial(cx, tnomeproc.getText());
          if(obj != null && !obj.isEmpty()){
               listar();
          }else{
               JOptionPane.showMessageDialog(null, "Nada encontrado");
          }
     }//GEN-LAST:event_botao_procurarActionPerformed

     private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
          if(obj != null && !obj.isEmpty()){
               comprar = obj.get(tabela.getSelectedRow());
               setaTelaComprar();
          }
     }//GEN-LAST:event_tabelaMouseClicked

     private void badicionar_fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badicionar_fornecedorActionPerformed
          novofornecedor = true;
          new JFGerenciaPessoa(cx).setVisible(true);
     }//GEN-LAST:event_badicionar_fornecedorActionPerformed

     private void badicionar_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badicionar_produtoActionPerformed
          new JFGerenciaProduto(cx).setVisible(true);
     }//GEN-LAST:event_badicionar_produtoActionPerformed

     private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
          if(novofornecedor == true){
               carregaFornecedor();
          }
     }//GEN-LAST:event_jTabbedPane1FocusGained

     private void cfornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cfornecedorMouseClicked
          if(novofornecedor == true){
               carregaFornecedor();
               novofornecedor = false;
          }
     }//GEN-LAST:event_cfornecedorMouseClicked

     private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          carregaFornecedor();
     }//GEN-LAST:event_formWindowOpened

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (Exception ex) {
               java.util.logging.Logger.getLogger(JFAvancadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFComprar().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton badicionar_fornecedor;
     private javax.swing.JButton badicionar_produto;
     private javax.swing.JButton bexcluir;
     private javax.swing.JButton botao_excluir;
     private javax.swing.JButton botao_inserir;
     private javax.swing.JButton botao_procurar;
     private javax.swing.JButton botao_sair;
     private javax.swing.JComboBox cfornecedor;
     private com.toedter.calendar.JDateChooser dcdtcompra;
     private com.toedter.calendar.JDateChooser dcdtvencimento;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JLabel lmensagem;
     private javax.swing.JLabel ltotalgasto;
     private javax.swing.JTable tabela;
     private javax.swing.JTable tabela_icompra;
     private javax.swing.JTextField tcodigobarra;
     private javax.swing.JTextField tnome_produto;
     private javax.swing.JTextField tnomeproc;
     private javax.swing.JTextField tparcela;
     private javax.swing.JTextField tpreco;
     private javax.swing.JTextField tquantidade;
     // End of variables declaration//GEN-END:variables

   /**lista tudo o que está na tabela**/  
    private void listar() {
            tabela.setModel(new TableModel(titulo, obj.size(), titulo.length));
            for(int i=0; i < obj.size(); i++){
                    tabela.setValueAt(obj.get(i).getCodigo(), i, 0);
                    tabela.setValueAt(mas.mascaraData("dd-MM-yyyy", obj.get(i).getData()), i, 1);
                    tabela.setValueAt(obj.get(i).getPessoa().getNome().toUpperCase(), i, 2);
                    tabela.setValueAt(Mascara.formatMoeda(obj.get(i).getValor()), i, 3);
            }
            tabela.setAutoCreateRowSorter(true);    
    }  

     private void setaComprar() {
          comprar.setPessoa(pessoa);
          comprar.setData(dcdtcompra.getDate());
          comprar.setVencimento(dcdtvencimento.getDate());
          String preco = ltotalgasto.getText();
          preco        = preco.replace("R$ ", "");          
          comprar.setValor(Mascara.formatToDouble(preco));
     }

     private void setaTelaComprar() {
          cfornecedor.setSelectedItem(comprar.getPessoa().getNome());
          tnome_produto.setText(produto.getNome());
          tpreco.setText(Mascara.formatMoeda(comprar.getValor()));
          tquantidade.setText(String.valueOf(produto.getQuantidade()));
     }
 
     
     private void carregaFornecedor() {
          obj_pessoa = pern.procuraTtipo(cx, "Fornecedores");
          if(obj_pessoa != null && !obj_pessoa.isEmpty()){
               cfornecedor.removeAllItems();
               for (Pessoa p : obj_pessoa) {
                    cfornecedor.addItem(p.getNome().toUpperCase());
               }
          }
     }
     
     private void listar_icompra() {
            tabela_icompra.setModel(new TableModel(titulo_icompra, obj_icompra.size(), titulo_icompra.length));
            for(int i = 0; i < obj_icompra.size(); i++){
                    tabela_icompra.setValueAt(obj_icompra.get(i).getProduto().getNome(), i, 0);
                    tabela_icompra.setValueAt(Mascara.formatMoeda(obj_icompra.get(i).getValor()), i, 1);
                    tabela_icompra.setValueAt(obj_icompra.get(i).getQuantidade(), i, 2);
            }
            tabela_icompra.setAutoCreateRowSorter(true); 
     }

     private void limpar() {
          tcodigobarra.setText("");
          tnome_produto.setText("");
          tpreco.setText("");
          tquantidade.setText("");
     }     

     private void setaTelaProduto() {
          tnome_produto.setText(produto.getNome());
          tpreco.setText(Mascara.formatMoeda(produto.getPrecovenda()));
          tquantidade.setText(String.valueOf(produto.getQuantidade()));
     }
     
     

}
