/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.UsuarioRN;
import persistencia.Conexao;
import recursos.utilitarios.TableModel;
import vo.Usuario;

/**
 *
 * @author ThyagoHenrique
 */
public class JFGerenciaUsuario extends javax.swing.JFrame {

     String              titulo[]            = new String[]{"Código", "Nome", "Nivel"};
     Usuario             usuario             = new Usuario();
     UsuarioRN           urn                 = new UsuarioRN();
     Conexao             cx                  = new Conexao();
     List<Usuario>       obj                 = new ArrayList();
     /**
      * Creates new form JFGerenciaUsuario
      */
     public JFGerenciaUsuario() {
          initComponents();
     }

     public JFGerenciaUsuario(Conexao cx) {
          initComponents();
          this.cx = cx;
     }     
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTabbedPane1 = new javax.swing.JTabbedPane();
          jPanel1 = new javax.swing.JPanel();
          jPanel3 = new javax.swing.JPanel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          tusuario = new javax.swing.JTextField();
          tsenha = new javax.swing.JPasswordField();
          jLabel6 = new javax.swing.JLabel();
          cestado2 = new javax.swing.JComboBox();
          jPanel5 = new javax.swing.JPanel();
          jLabel7 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          tsegundonome = new javax.swing.JTextField();
          tprimeironome = new javax.swing.JTextField();
          jLabel10 = new javax.swing.JLabel();
          temail2 = new javax.swing.JTextField();
          binserir_usuario = new javax.swing.JButton();
          bupdate_usuario = new javax.swing.JButton();
          bexcluir_usuario = new javax.swing.JButton();
          bsair2 = new javax.swing.JButton();
          blimpar = new javax.swing.JButton();
          jPanel6 = new javax.swing.JPanel();
          jLabel21 = new javax.swing.JLabel();
          tnomeproc = new javax.swing.JTextField();
          jScrollPane1 = new javax.swing.JScrollPane();
          tabela = new javax.swing.JTable();
          bprocurar = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Gerencia de Usuários");

          jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações de entrada")));

          jLabel3.setText("Usuário");

          jLabel4.setText("Senha");

          tusuario.setToolTipText("Login funciona no sistema e no site");

          tsenha.setToolTipText("Só funciona no sistema");

          jLabel6.setText("Estado");

          cestado2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
          cestado2.setToolTipText("Estado dentro do sistema e do site");

          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
          jPanel3.setLayout(jPanel3Layout);
          jPanel3Layout.setHorizontalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel3)
                         .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(tusuario)
                         .addComponent(cestado2, 0, 161, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel3Layout.setVerticalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(jLabel4)
                         .addComponent(tusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(tsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(cestado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel6))
                    .addContainerGap(27, Short.MAX_VALUE))
          );

          jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Identificação"));

          jLabel7.setText("Primeiro nome");

          jLabel8.setText("Segundo nome");

          jLabel10.setText("E-mail");

          javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
          jPanel5.setLayout(jPanel5Layout);
          jPanel5Layout.setHorizontalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                         .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(tprimeironome)
                         .addComponent(temail2))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(tsegundonome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33))
          );
          jPanel5Layout.setVerticalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel7)
                         .addComponent(jLabel8)
                         .addComponent(tsegundonome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(tprimeironome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel10)
                         .addComponent(temail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          binserir_usuario.setText("Inserir");
          binserir_usuario.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserir_usuarioActionPerformed(evt);
               }
          });

          bupdate_usuario.setText("update");
          bupdate_usuario.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bupdate_usuarioActionPerformed(evt);
               }
          });

          bexcluir_usuario.setText("Excluir");
          bexcluir_usuario.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluir_usuarioActionPerformed(evt);
               }
          });

          bsair2.setText("Sair");
          bsair2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bsair2ActionPerformed(evt);
               }
          });

          blimpar.setText("Limpar");
          blimpar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    blimparActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(blimpar)
                    .addGap(18, 18, 18)
                    .addComponent(binserir_usuario)
                    .addGap(18, 18, 18)
                    .addComponent(bupdate_usuario)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bexcluir_usuario)
                    .addGap(18, 18, 18)
                    .addComponent(bsair2)
                    .addContainerGap(166, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(binserir_usuario)
                         .addComponent(bupdate_usuario)
                         .addComponent(bexcluir_usuario)
                         .addComponent(bsair2)
                         .addComponent(blimpar))
                    .addContainerGap(113, Short.MAX_VALUE))
          );

          jTabbedPane1.addTab("Informações usuário", jPanel1);

          jLabel21.setText("Nome");

          tabela.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Código", "Nome", "CPF", "Telefone"
               }
          ));
          tabela.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelaMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tabela);

          bprocurar.setText("Procurar");
          bprocurar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bprocurarActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
          jPanel6.setLayout(jPanel6Layout);
          jPanel6Layout.setHorizontalGroup(
               jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane1)
                         .addGroup(jPanel6Layout.createSequentialGroup()
                              .addComponent(jLabel21)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(bprocurar)
                              .addGap(0, 4, Short.MAX_VALUE)))
                    .addContainerGap())
          );
          jPanel6Layout.setVerticalGroup(
               jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel21)
                         .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(bprocurar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addContainerGap())
          );

          jTabbedPane1.addTab("Procurar", jPanel6);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 744, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 423, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void binserir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserir_usuarioActionPerformed
          usuario = new Usuario();
          setaUsuario();
          String msg = urn.inserirUsuario(cx, usuario);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               JOptionPane.showMessageDialog(null, "Ação efetuada com sucesso");
          }
     }//GEN-LAST:event_binserir_usuarioActionPerformed

     private void bsair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsair2ActionPerformed
          dispose();
     }//GEN-LAST:event_bsair2ActionPerformed

     private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
          usuario = obj.get(tabela.getSelectedRow());
          if(usuario != null && usuario.getPrimeironome() != null){
               setaTelaUsuario();
          }
     }//GEN-LAST:event_tabelaMouseClicked

     private void bprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprocurarActionPerformed
          obj = urn.procuraNomeParcial(cx, tnomeproc.getText());
          if(obj != null && !obj.isEmpty()){
               listar();
          }else{
               JOptionPane.showMessageDialog(null, "Nada encontrado");
          }
     }//GEN-LAST:event_bprocurarActionPerformed

     private void bupdate_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdate_usuarioActionPerformed
          setaUsuario();
          String msg = urn.updateUsuario(cx, usuario);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               JOptionPane.showMessageDialog(null, "Ação efetuada com sucesso");
          }
     }//GEN-LAST:event_bupdate_usuarioActionPerformed

     private void bexcluir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluir_usuarioActionPerformed
          if(usuario != null && usuario.getCodigo() != null){
               String msg = urn.excluirUsuario(cx, usuario);
               if(msg != null && !msg.isEmpty()){
                    JOptionPane.showMessageDialog(null, msg);
               }else{
                    JOptionPane.showMessageDialog(null, "Ação efetuada com sucesso");
               }
          }
     }//GEN-LAST:event_bexcluir_usuarioActionPerformed

     private void blimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimparActionPerformed
          limparTelaUsuario();
     }//GEN-LAST:event_blimparActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFGerenciaUsuario().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton bupdate_usuario;
     private javax.swing.JButton bexcluir_usuario;
     private javax.swing.JButton binserir_usuario;
     private javax.swing.JButton blimpar;
     private javax.swing.JButton bprocurar;
     private javax.swing.JButton bsair2;
     private javax.swing.JComboBox cestado2;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel21;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JPanel jPanel5;
     private javax.swing.JPanel jPanel6;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JTable tabela;
     private javax.swing.JTextField temail2;
     private javax.swing.JTextField tnomeproc;
     private javax.swing.JTextField tprimeironome;
     private javax.swing.JTextField tsegundonome;
     private javax.swing.JPasswordField tsenha;
     private javax.swing.JTextField tusuario;
     // End of variables declaration//GEN-END:variables


     private void setaUsuario() {
          usuario.setEmail(temail2.getText());
          if(cestado2.getSelectedItem().toString().equals("Ativo")){
               usuario.setEstado(1);
          }
          if(cestado2.getSelectedItem().toString().equals("Inativo")){
               usuario.setEstado(0);
          }
          usuario.setPrimeironome(tprimeironome.getText().toUpperCase());
          usuario.setUltimonome(tsegundonome.getText().toUpperCase());
          usuario.setUsuario(tusuario.getText());
          usuario.setSenha(tsenha.getText());
     }
    
     private void setaTelaUsuario(){
          temail2.setText(usuario.getEmail());
          if(usuario.getEstado() == 1){
               cestado2.setSelectedItem("Ativo");
          }
          if(usuario.getEstado() == 2){
               cestado2.setSelectedItem("Inativo");
          }     
          tprimeironome.setText(usuario.getPrimeironome().toUpperCase());
          tsegundonome.setText(usuario.getUltimonome().toUpperCase());
          tusuario.setText(usuario.getUsuario());
          tsenha.setText(usuario.getSenha());
     }
     
   /**lista tudo o que está na tabela**/  
    private void listar() {
            tabela.setModel(new TableModel(titulo, obj.size(), titulo.length));
            for(int i = 0; i < obj.size(); i++){
                    tabela.setValueAt(obj.get(i).getCodigo(), i, 0);
                    tabela.setValueAt(obj.get(i).getPrimeironome().toUpperCase() + " " + obj.get(i).getUltimonome(), i, 1);
                    tabela.setValueAt(obj.get(i).getUserrole(), i, 2);
            }
            tabela.setAutoCreateRowSorter(true);    
    }   
    
     private void limparTelaUsuario(){
          temail2.setText("");
          cestado2.setSelectedItem("");
          tprimeironome.setText("");
          tsegundonome.setText("");
          tusuario.setText("");
          tsenha.setText("");
     }    
}
