/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.EnderecoRN;
import negocio.EstadoRN;
import negocio.UsuarioRN;
import negocio.VendedorRN;
import persistencia.Conexao;
import recursos.utilitarios.Cep;
import recursos.utilitarios.Mascara;
import recursos.utilitarios.TableModel;
import vo.CepServiceVO;
import vo.Endereco;
import vo.Estado;
import vo.Usuario;
import vo.Vendedor;

/**
 *
 * @author ThyagoHenrique
 */
public class JFGerenciaVendedor extends javax.swing.JFrame {

     String              titulo[]            = new String[]{"Código", "Nome", "CPF", "Telefone"};
     String              titulo_endereco[]   = new String[]{"Código", "CEP", "Endereço", "Estado"};
     TableModel          tm_endereco         = new TableModel(titulo_endereco, 1, titulo_endereco.length);  
     TableModel          tm                  = new TableModel(titulo, 1, titulo.length);       
     VendedorRN          prn                 = new VendedorRN();
     Vendedor            vendedor            = new Vendedor();
     List<Vendedor>      obj                 = new ArrayList();
     Endereco            endereco            = new Endereco();
     EnderecoRN          ern                 = new EnderecoRN();
     List<Endereco>      obj_endereco        = new ArrayList();
     List<Estado>        obj_estado          = new ArrayList();
     EstadoRN            esrn                = new EstadoRN();
     Estado              estado              = new Estado();
     Conexao             cx;
     Mascara             mas                 = new Mascara();
     UsuarioRN           urn                 = new UsuarioRN();
     Usuario             usuario             = new Usuario();
     
     /**
      * Creates new form JFGerenciaVendedor
      */
     public JFGerenciaVendedor() {
          initComponents();
     }
     
     public JFGerenciaVendedor(Conexao cx) {
          initComponents();
          this.cx = cx;
          tabela.setModel(tm);
     }   
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          tpinformacoesusuario = new javax.swing.JTabbedPane();
          jPanel2 = new javax.swing.JPanel();
          jPanel4 = new javax.swing.JPanel();
          jLabel5 = new javax.swing.JLabel();
          tnome = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          tlucro = new javax.swing.JTextField();
          pcontato = new javax.swing.JPanel();
          jLabel9 = new javax.swing.JLabel();
          ttelefone = new javax.swing.JTextField();
          jLabel11 = new javax.swing.JLabel();
          temail = new javax.swing.JTextField();
          pendereco = new javax.swing.JPanel();
          jLabel13 = new javax.swing.JLabel();
          trua = new javax.swing.JTextField();
          jLabel14 = new javax.swing.JLabel();
          jTextField4 = new javax.swing.JTextField();
          jLabel15 = new javax.swing.JLabel();
          tbairro = new javax.swing.JTextField();
          jLabel18 = new javax.swing.JLabel();
          tcidade = new javax.swing.JTextField();
          jLabel19 = new javax.swing.JLabel();
          cestado = new javax.swing.JComboBox();
          jLabel20 = new javax.swing.JLabel();
          tcep = new javax.swing.JTextField();
          jLabel1 = new javax.swing.JLabel();
          tpais = new javax.swing.JTextField();
          bupdate = new javax.swing.JButton();
          bsair = new javax.swing.JButton();
          bexcluir = new javax.swing.JButton();
          binserir = new javax.swing.JButton();
          jPanel1 = new javax.swing.JPanel();
          jPanel3 = new javax.swing.JPanel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          tusuario = new javax.swing.JTextField();
          tsenha = new javax.swing.JPasswordField();
          jLabel6 = new javax.swing.JLabel();
          cestado2 = new javax.swing.JComboBox();
          jPanel5 = new javax.swing.JPanel();
          jLabel7 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          tsegundonome = new javax.swing.JTextField();
          tprimeironome = new javax.swing.JTextField();
          jLabel10 = new javax.swing.JLabel();
          temail2 = new javax.swing.JTextField();
          binserir_usuario = new javax.swing.JButton();
          bupdate_usuario = new javax.swing.JButton();
          bexcluir_usuario = new javax.swing.JButton();
          bsair2 = new javax.swing.JButton();
          jPanel6 = new javax.swing.JPanel();
          jLabel21 = new javax.swing.JLabel();
          tnomeproc = new javax.swing.JTextField();
          jScrollPane1 = new javax.swing.JScrollPane();
          tabela = new javax.swing.JTable();
          bprocurar = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Gerencia Vendedores");
          addWindowListener(new java.awt.event.WindowAdapter() {
               public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
               }
          });

          jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações Pessoais"));

          jLabel5.setText("Nome");

          jLabel2.setText("Margem lucro");

          tlucro.setToolTipText("Margem porcentual de lucro");

          javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
          jPanel4.setLayout(jPanel4Layout);
          jPanel4Layout.setHorizontalGroup(
               jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tlucro, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE))
          );
          jPanel4Layout.setVerticalGroup(
               jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel2)
                         .addComponent(tlucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 14, Short.MAX_VALUE))
          );

          pcontato.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações para Contato"));

          jLabel9.setText("Telefone");

          ttelefone.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    ttelefoneKeyTyped(evt);
               }
          });

          jLabel11.setText("E-mail");

          javax.swing.GroupLayout pcontatoLayout = new javax.swing.GroupLayout(pcontato);
          pcontato.setLayout(pcontatoLayout);
          pcontatoLayout.setHorizontalGroup(
               pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pcontatoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(41, 41, 41)
                    .addComponent(jLabel11)
                    .addGap(36, 36, 36)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE))
          );
          pcontatoLayout.setVerticalGroup(
               pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pcontatoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel11)
                              .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel9)
                              .addComponent(ttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pendereco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Endereço"));

          jLabel13.setText("Rua");

          jLabel14.setText("NUM");

          jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextField4KeyTyped(evt);
               }
          });

          jLabel15.setText("Bairro");

          jLabel18.setText("Cidade");

          jLabel19.setText("UF");

          cestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "GO", "ES", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RO", "RR", "RS", "SP", "SC", "SE", "TO" }));
          cestado.setSelectedItem("PR");
          cestado.setToolTipText("Sigla do estado ao qual pertence");

          jLabel20.setText("CEP");

          tcep.setToolTipText("CEP's válidos podem fazer a volta de endereço via internet");
          tcep.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusLost(java.awt.event.FocusEvent evt) {
                    tcepFocusLost(evt);
               }
          });
          tcep.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    tcepKeyTyped(evt);
               }
          });

          jLabel1.setText("Pais");

          javax.swing.GroupLayout penderecoLayout = new javax.swing.GroupLayout(pendereco);
          pendereco.setLayout(penderecoLayout);
          penderecoLayout.setHorizontalGroup(
               penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(penderecoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel15)
                         .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(tcep, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                         .addComponent(tbairro)
                         .addComponent(tpais))
                    .addGap(18, 18, 18)
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel13)
                         .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(penderecoLayout.createSequentialGroup()
                              .addComponent(trua, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(29, 29, 29)
                              .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(penderecoLayout.createSequentialGroup()
                              .addComponent(cestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(tcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(66, 66, 66))
          );
          penderecoLayout.setVerticalGroup(
               penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(penderecoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel20)
                         .addComponent(tcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel13)
                         .addComponent(trua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel14)
                         .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel15)
                         .addComponent(tbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel19)
                         .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel18)
                         .addComponent(tcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(tpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(22, Short.MAX_VALUE))
          );

          bupdate.setText("update");
          bupdate.setToolTipText("update pessoa");
          bupdate.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bupdateActionPerformed(evt);
               }
          });

          bsair.setText("Sair");
          bsair.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bsairActionPerformed(evt);
               }
          });

          bexcluir.setText("Excluir");
          bexcluir.setToolTipText("Excluir pessoa");
          bexcluir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluirActionPerformed(evt);
               }
          });

          binserir.setText("Inserir");
          binserir.setToolTipText("Inserir pessoa");
          binserir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserirActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(pcontato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(pendereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(binserir)
                    .addGap(26, 26, 26)
                    .addComponent(bupdate)
                    .addGap(26, 26, 26)
                    .addComponent(bexcluir)
                    .addGap(28, 28, 28)
                    .addComponent(bsair)
                    .addGap(14, 14, 14))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addComponent(pcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(pendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(80, 80, 80)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bupdate)
                         .addComponent(bsair)
                         .addComponent(bexcluir)
                         .addComponent(binserir))
                    .addContainerGap(22, Short.MAX_VALUE))
          );

          tpinformacoesusuario.addTab("Cadastro", jPanel2);

          jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações de entrada")));

          jLabel3.setText("Usuário");

          jLabel4.setText("Senha");

          tusuario.setToolTipText("Login funciona no sistema e no site");

          tsenha.setToolTipText("Só funciona no sistema");

          jLabel6.setText("Estado");

          cestado2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
          cestado2.setToolTipText("Estado dentro do sistema e do site");

          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
          jPanel3.setLayout(jPanel3Layout);
          jPanel3Layout.setHorizontalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel3)
                         .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(tusuario)
                         .addComponent(cestado2, 0, 161, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel3Layout.setVerticalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(jLabel4)
                         .addComponent(tusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(tsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(cestado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel6))
                    .addContainerGap(27, Short.MAX_VALUE))
          );

          jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Identificação"));

          jLabel7.setText("Primeiro nome");

          jLabel8.setText("Segundo nome");

          jLabel10.setText("E-mail");

          javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
          jPanel5.setLayout(jPanel5Layout);
          jPanel5Layout.setHorizontalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                         .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(tprimeironome)
                         .addComponent(temail2))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(tsegundonome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33))
          );
          jPanel5Layout.setVerticalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel7)
                         .addComponent(jLabel8)
                         .addComponent(tsegundonome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(tprimeironome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel10)
                         .addComponent(temail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          binserir_usuario.setText("Inserir");
          binserir_usuario.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserir_usuarioActionPerformed(evt);
               }
          });

          bupdate_usuario.setText("update");
          bupdate_usuario.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bupdate_usuarioActionPerformed(evt);
               }
          });

          bexcluir_usuario.setText("Excluir");
          bexcluir_usuario.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluir_usuarioActionPerformed(evt);
               }
          });

          bsair2.setText("Sair");
          bsair2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bsair2ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(285, 285, 285)
                    .addComponent(binserir_usuario)
                    .addGap(18, 18, 18)
                    .addComponent(bupdate_usuario)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bexcluir_usuario)
                    .addGap(18, 18, 18)
                    .addComponent(bsair2)
                    .addContainerGap(161, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(binserir_usuario)
                         .addComponent(bupdate_usuario)
                         .addComponent(bexcluir_usuario)
                         .addComponent(bsair2))
                    .addContainerGap(141, Short.MAX_VALUE))
          );

          tpinformacoesusuario.addTab("Informações usuário", jPanel1);

          jLabel21.setText("Nome");

          tabela.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Código", "Nome", "CPF", "Telefone"
               }
          ));
          tabela.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelaMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tabela);

          bprocurar.setText("Procurar");
          bprocurar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bprocurarActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
          jPanel6.setLayout(jPanel6Layout);
          jPanel6Layout.setHorizontalGroup(
               jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane1)
                         .addGroup(jPanel6Layout.createSequentialGroup()
                              .addComponent(jLabel21)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(bprocurar)
                              .addGap(0, 9, Short.MAX_VALUE)))
                    .addContainerGap())
          );
          jPanel6Layout.setVerticalGroup(
               jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel21)
                         .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(bprocurar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addContainerGap())
          );

          tpinformacoesusuario.addTab("Procurar", jPanel6);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tpinformacoesusuario)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(tpinformacoesusuario)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void ttelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttelefoneKeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_ttelefoneKeyTyped

     private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_jTextField4KeyTyped

     private void tcepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tcepFocusLost
          Cep   ser = new Cep();
          CepServiceVO cep = ser.procuraCEP(tcep.getText());
          tcidade.setText(cep.getCidade());
          tbairro.setText(cep.getBairro());
          trua.setText(cep.getTipo_logradouro() + " " +cep.getLogradouro());
          if(cep.getUf().length() <= 3){
               estado = esrn.procuraSigla(cx, cep.getUf());
               cestado.setSelectedItem(estado.getNome());
          }
     }//GEN-LAST:event_tcepFocusLost

     private void tcepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcepKeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_tcepKeyTyped

     private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
          setaVendedor();
          String msg = prn.updateVendedor(cx, vendedor);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               for(int i = 0; i < obj.size(); i++){
                    if(obj.get(i).getCodigo() == vendedor.getCodigo()){
                         obj.set(i, vendedor);
                         listar();
                         break;
                    }
               }
               JOptionPane.showMessageDialog(null, "Atualizado com sucesso");
          }
     }//GEN-LAST:event_bupdateActionPerformed

     private void bsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsairActionPerformed
          this.dispose();
     }//GEN-LAST:event_bsairActionPerformed

     private void bexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluirActionPerformed
          String msg      = "";
          int    response = JOptionPane.showConfirmDialog(null, "Tem certeza disso,\n"
               + "Você quer excluir?", "Confirmação de excluir:",
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if (response == JOptionPane.YES_OPTION){
               if(vendedor != null && vendedor.getCodigo() != null){
                    msg = prn.excluirVendedor(cx, vendedor);
               }else{
                    msg = "Para excluir escolha antes uma vendedor que tenha sido gravada no banco";
               }
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.remove(vendedor);
               listar();
               JOptionPane.showMessageDialog(null, "Excluido com sucesso");
          }
     }//GEN-LAST:event_bexcluirActionPerformed

     private void binserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserirActionPerformed
          vendedor = new Vendedor();
          setaVendedor();
          String msg = prn.inserirVendedor(cx, vendedor);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.add(vendedor);
               listar();
               JOptionPane.showMessageDialog(null, "Inserido com sucesso");
          }
     }//GEN-LAST:event_binserirActionPerformed

     private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
          vendedor = obj.get(tabela.getSelectedRow());
          if(vendedor != null && vendedor.getNome() != null){
               setaTela();
               usuario = urn.procuraVendedor(cx, vendedor.getCodigo());
               if(usuario != null && usuario.getCodigo() != null){
                    setaTelaUsuario();
               }else{
                    limparTelaUsuario();
               }
          }
     }//GEN-LAST:event_tabelaMouseClicked

     private void bprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprocurarActionPerformed
          obj = prn.procuraNomeParcial(cx, tnomeproc.getText());
          if(obj != null && !obj.isEmpty()){
               listar();
          }else{
               JOptionPane.showMessageDialog(null, "Nada encontrado");
          }
     }//GEN-LAST:event_bprocurarActionPerformed

     private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          carregaEstado();
     }//GEN-LAST:event_formWindowOpened

     private void bsair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsair2ActionPerformed
          dispose();
     }//GEN-LAST:event_bsair2ActionPerformed

     private void binserir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserir_usuarioActionPerformed
          usuario = new Usuario();
          setaUsuario();
          String msg = urn.inserirUsuario(cx, usuario);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               JOptionPane.showMessageDialog(null, "Ação efetuada com sucesso");
          }
     }//GEN-LAST:event_binserir_usuarioActionPerformed

     private void bupdate_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdate_usuarioActionPerformed
          setaUsuario();
          String msg = urn.updateUsuario(cx, usuario);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               JOptionPane.showMessageDialog(null, "Ação efetuada com sucesso");
          }
     }//GEN-LAST:event_bupdate_usuarioActionPerformed

     private void bexcluir_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluir_usuarioActionPerformed
          if(usuario != null && usuario.getCodigo() != null){
               String msg = urn.excluirUsuario(cx, usuario);
               if(msg != null && !msg.isEmpty()){
                    JOptionPane.showMessageDialog(null, msg);
               }else{
                    JOptionPane.showMessageDialog(null, "Ação efetuada com sucesso");
               }
          }
     }//GEN-LAST:event_bexcluir_usuarioActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFGerenciaVendedor().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton bupdate;
     private javax.swing.JButton bupdate_usuario;
     private javax.swing.JButton bexcluir;
     private javax.swing.JButton bexcluir_usuario;
     private javax.swing.JButton binserir;
     private javax.swing.JButton binserir_usuario;
     private javax.swing.JButton bprocurar;
     private javax.swing.JButton bsair;
     private javax.swing.JButton bsair2;
     private javax.swing.JComboBox cestado;
     private javax.swing.JComboBox cestado2;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel19;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel20;
     private javax.swing.JLabel jLabel21;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JPanel jPanel4;
     private javax.swing.JPanel jPanel5;
     private javax.swing.JPanel jPanel6;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTextField jTextField4;
     private javax.swing.JPanel pcontato;
     private javax.swing.JPanel pendereco;
     private javax.swing.JTable tabela;
     private javax.swing.JTextField tbairro;
     private javax.swing.JTextField tcep;
     private javax.swing.JTextField tcidade;
     private javax.swing.JTextField temail;
     private javax.swing.JTextField temail2;
     private javax.swing.JTextField tlucro;
     private javax.swing.JTextField tnome;
     private javax.swing.JTextField tnomeproc;
     private javax.swing.JTextField tpais;
     private javax.swing.JTabbedPane tpinformacoesusuario;
     private javax.swing.JTextField tprimeironome;
     private javax.swing.JTextField trua;
     private javax.swing.JTextField tsegundonome;
     private javax.swing.JPasswordField tsenha;
     private javax.swing.JTextField ttelefone;
     private javax.swing.JTextField tusuario;
     // End of variables declaration//GEN-END:variables

     /**seta informações da tela no objeto vendedor**/
     private void setaVendedor() {
          vendedor.setEmail(temail.getText());
          vendedor.setNome(tnome.getText());
          vendedor.setTelefone(ttelefone.getText());
          vendedor.setCep(tcep.getText());
          vendedor.setCidade(tcidade.getText());
          vendedor.setEndereço(trua.getText());
          vendedor.setEstado(cestado.getSelectedItem().toString());
          vendedor.setComissao(mas.TiraVirgula(tlucro.getText()));
          vendedor.setPais(tpais.getText());
          vendedor.setTelefone(ttelefone.getText());
     }
     
     /**seta informações do objeto vendedor na tela**/
     private void setaTela() {
          temail.setText(vendedor.getEmail());
          tnome.setText(vendedor.getNome());
          ttelefone.setText(vendedor.getTelefone());
          tcep.setText(vendedor.getCep());
          tcidade.setText(vendedor.getCidade());
          trua.setText(vendedor.getEndereço());
          cestado.setSelectedItem(vendedor.getEstado());
          tlucro.setText(mas.ColocaVirgula(vendedor.getComissao()));
          tpais.setText(vendedor.getPais());
          ttelefone.setText(vendedor.getTelefone());
     }     

   /**lista tudo o que está na tabela**/  
    private void listar() {
            tabela.setModel(new TableModel(titulo, obj.size(), titulo.length));
            for(int i = 0; i < obj.size(); i++){
                    tabela.setValueAt(obj.get(i).getCodigo(), i, 0);
                    tabela.setValueAt(obj.get(i).getNome().toUpperCase(), i, 1);
                    tabela.setValueAt(obj.get(i).getTelefone(), i, 3);
            }
            tabela.setAutoCreateRowSorter(true);    
    }  

     private void carregaEstado() {
          if(obj_estado == null || obj_estado.isEmpty()){
               obj_estado = esrn.procuraTodos(cx);
               if(obj_estado != null && !obj_estado.isEmpty()){
                    cestado.removeAllItems();
                    for (Estado e : obj_estado) {
                         cestado.addItem(e.getNome().toUpperCase());
                    }                    
               }
          }
     }

     private void setaUsuario() {
          usuario.setEmail(temail2.getText());
          if(cestado2.getSelectedItem().toString().equals("Ativo")){
               usuario.setEstado(1);
          }
          if(cestado2.getSelectedItem().toString().equals("Inativo")){
               usuario.setEstado(0);
          }
          usuario.setPrimeironome(tprimeironome.getText().toUpperCase());
          usuario.setUltimonome(tsegundonome.getText().toUpperCase());
          usuario.setUsuario(tusuario.getText());
          usuario.setSenha(tsenha.getText());
          usuario.setCodvendedor(vendedor.getCodigo());
          usuario.setImportsenha("");
          usuario.setToken("");
          usuario.setUsertoken("");
          usuario.setUserrole("");
     }
    
     private void setaTelaUsuario(){
          temail2.setText(usuario.getEmail());
          if(usuario.getEstado() == 1){
               cestado2.setSelectedItem("Ativo");
          }
          if(usuario.getEstado() == 2){
               cestado2.setSelectedItem("Inativo");
          }     
          tprimeironome.setText(usuario.getPrimeironome().toUpperCase());
          tsegundonome.setText(usuario.getUltimonome().toUpperCase());
          tusuario.setText(usuario.getUsuario());
          tsenha.setText(usuario.getSenha());
     }
     
     private void limparTelaUsuario(){
          temail2.setText("");
          cestado2.setSelectedItem("");
          tprimeironome.setText("");
          tsegundonome.setText("");
          tusuario.setText("");
          tsenha.setText("");
     }
    
}
