/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.InputStream;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import negocio.EnderecoRN;
import negocio.EstadoRN;
import negocio.PessoaRN;
import negocio.TipoPessoaRN;
import persistencia.Conexao;
import recursos.utilitarios.Cep;
import recursos.utilitarios.Mascara;
import recursos.utilitarios.Relatorio;
import recursos.utilitarios.TableModel;
import vo.CepServiceVO;
import vo.Endereco;
import vo.Estado;
import vo.Pessoa;
import vo.TipoPessoa;

/**
 *
 * @author ThyagoHenrique
 */
public class JFGerenciaPessoa extends javax.swing.JFrame {

     String              titulo[]            = new String[]{"Código", "Nome", "CPF", "Telefone"};
     String              titulo_endereco[]   = new String[]{"Código", "CEP", "Endereço", "Estado"};
     TableModel          tm_endereco         = new TableModel(titulo_endereco, 1, titulo_endereco.length);  
     TableModel          tm                  = new TableModel(titulo, 1, titulo.length);       
     PessoaRN            prn                 = new PessoaRN();
     Pessoa              pessoa              = new Pessoa();
     List<Pessoa>        obj                 = new ArrayList();
     TipoPessoa          tipo                = new TipoPessoa();
     TipoPessoaRN        trn                 = new TipoPessoaRN();
     List<TipoPessoa>    obj_tipo            = new ArrayList();
     Endereco            endereco            = new Endereco();
     EnderecoRN          ern                 = new EnderecoRN();
     List<Endereco>      obj_endereco        = new ArrayList();
     List<Estado>        obj_estado          = new ArrayList();
     EstadoRN            esrn                = new EstadoRN();
     Estado              estado              = new Estado();
     Conexao             cx;
     private boolean     novotipo            = false;
     Mascara             mas                 = new Mascara();
     
     /**
      * Creates new form JFGerenciaPessoa
      */
     public JFGerenciaPessoa() {
          initComponents();
     }
     
     public JFGerenciaPessoa(Conexao cx) {
          initComponents();
          this.cx = cx;
          tabela.setModel(tm);
          tabela_endereco.setModel(tm_endereco);
     }   
     
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTabbedPane2 = new javax.swing.JTabbedPane();
          jPanel2 = new javax.swing.JPanel();
          jPanel4 = new javax.swing.JPanel();
          jLabel5 = new javax.swing.JLabel();
          jLabel6 = new javax.swing.JLabel();
          jLabel7 = new javax.swing.JLabel();
          jLabel8 = new javax.swing.JLabel();
          tnome = new javax.swing.JTextField();
          dcnascimento = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
          tcpf = new javax.swing.JTextField();
          trg = new javax.swing.JTextField();
          jLabel16 = new javax.swing.JLabel();
          tsobrenome = new javax.swing.JTextField();
          pcontato = new javax.swing.JPanel();
          jLabel9 = new javax.swing.JLabel();
          jLabel10 = new javax.swing.JLabel();
          ttelefone = new javax.swing.JTextField();
          tcelular = new javax.swing.JTextField();
          jLabel11 = new javax.swing.JLabel();
          temail = new javax.swing.JTextField();
          jLabel12 = new javax.swing.JLabel();
          jTextField2 = new javax.swing.JTextField();
          jLabel17 = new javax.swing.JLabel();
          tsenha = new javax.swing.JPasswordField();
          pendereco = new javax.swing.JPanel();
          jLabel13 = new javax.swing.JLabel();
          trua = new javax.swing.JTextField();
          jLabel14 = new javax.swing.JLabel();
          jTextField4 = new javax.swing.JTextField();
          jLabel15 = new javax.swing.JLabel();
          tbairro = new javax.swing.JTextField();
          jLabel18 = new javax.swing.JLabel();
          tcidade = new javax.swing.JTextField();
          jLabel19 = new javax.swing.JLabel();
          cestado = new javax.swing.JComboBox();
          jLabel20 = new javax.swing.JLabel();
          tcep = new javax.swing.JTextField();
          bexcluir_endereco = new javax.swing.JButton();
          bupdate_endereco = new javax.swing.JButton();
          binserir_endereco = new javax.swing.JButton();
          bupdate = new javax.swing.JButton();
          bsair = new javax.swing.JButton();
          bexcluir = new javax.swing.JButton();
          binserir = new javax.swing.JButton();
          label_pessoa = new javax.swing.JLabel();
          ctipopessoa = new javax.swing.JComboBox();
          bimprimir = new javax.swing.JButton();
          binserir_tipo = new javax.swing.JButton();
          jPanel5 = new javax.swing.JPanel();
          jScrollPane2 = new javax.swing.JScrollPane();
          tabela_endereco = new javax.swing.JTable();
          jPanel6 = new javax.swing.JPanel();
          jLabel21 = new javax.swing.JLabel();
          tnomeproc = new javax.swing.JTextField();
          jScrollPane1 = new javax.swing.JScrollPane();
          tabela = new javax.swing.JTable();
          bprocurar = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Gerencia Pessoas");
          addWindowListener(new java.awt.event.WindowAdapter() {
               public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
               }
          });

          jTabbedPane2.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusGained(java.awt.event.FocusEvent evt) {
                    jTabbedPane2FocusGained(evt);
               }
          });

          jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusGained(java.awt.event.FocusEvent evt) {
                    jPanel2FocusGained(evt);
               }
          });

          jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações Pessoais"));

          jLabel5.setText("Nome");

          jLabel6.setText("CPF");

          jLabel7.setText("RG");

          jLabel8.setText("Nascimento");

          tcpf.setToolTipText("Sem pontos, nem traços");
          tcpf.setName(""); // NOI18N
          tcpf.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusLost(java.awt.event.FocusEvent evt) {
                    tcpfFocusLost(evt);
               }
          });
          tcpf.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    tcpfKeyTyped(evt);
               }
          });

          jLabel16.setText("Sobrenome");

          javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
          jPanel4.setLayout(jPanel4Layout);
          jPanel4Layout.setHorizontalGroup(
               jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                         .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel4Layout.createSequentialGroup()
                              .addComponent(tcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(trg, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(26, 26, 26)
                              .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(dcnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(jPanel4Layout.createSequentialGroup()
                              .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(tsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(43, Short.MAX_VALUE))
          );
          jPanel4Layout.setVerticalGroup(
               jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel5)
                         .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel16)
                         .addComponent(tsobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(jLabel6)
                              .addComponent(jLabel7)
                              .addComponent(tcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(trg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(jLabel8))
                         .addComponent(dcnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 8, Short.MAX_VALUE))
          );

          pcontato.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações para Contato"));

          jLabel9.setText("Telefone");

          jLabel10.setText("Celular");

          ttelefone.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    ttelefoneKeyTyped(evt);
               }
          });

          tcelular.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    tcelularKeyTyped(evt);
               }
          });

          jLabel11.setText("E-mail");

          jLabel12.setText("Falar com");

          jLabel17.setText("Senha");

          tsenha.setToolTipText("senha para o site, caso queira");

          javax.swing.GroupLayout pcontatoLayout = new javax.swing.GroupLayout(pcontato);
          pcontato.setLayout(pcontatoLayout);
          pcontatoLayout.setHorizontalGroup(
               pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pcontatoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addGroup(pcontatoLayout.createSequentialGroup()
                              .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(ttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(jLabel12)
                              .addGap(31, 31, 31)
                              .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(pcontatoLayout.createSequentialGroup()
                              .addComponent(jLabel11)
                              .addGap(36, 36, 36)
                              .addComponent(temail)))
                    .addGap(40, 40, 40)
                    .addGroup(pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(tcelular, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                         .addComponent(tsenha))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          pcontatoLayout.setVerticalGroup(
               pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(pcontatoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel9)
                         .addComponent(ttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel10)
                         .addComponent(tcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel12)
                         .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pcontatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel11)
                         .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel17)
                         .addComponent(tsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pendereco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Endereço"));

          jLabel13.setText("Rua");

          jLabel14.setText("NUM");

          jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    jTextField4KeyTyped(evt);
               }
          });

          jLabel15.setText("Bairro");

          jLabel18.setText("Cidade");

          jLabel19.setText("UF");

          cestado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "GO", "ES", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RO", "RR", "RS", "SP", "SC", "SE", "TO" }));
          cestado.setSelectedItem("PR");
          cestado.setToolTipText("Sigla do estado ao qual pertence");

          jLabel20.setText("CEP");

          tcep.setToolTipText("CEP's válidos podem fazer a volta de endereço via internet");
          tcep.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusLost(java.awt.event.FocusEvent evt) {
                    tcepFocusLost(evt);
               }
          });
          tcep.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyTyped(java.awt.event.KeyEvent evt) {
                    tcepKeyTyped(evt);
               }
          });

          bexcluir_endereco.setText("Excluir");
          bexcluir_endereco.setToolTipText("Excluir endereço");
          bexcluir_endereco.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluir_enderecoActionPerformed(evt);
               }
          });

          bupdate_endereco.setText("update");
          bupdate_endereco.setToolTipText("update endereço");
          bupdate_endereco.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bupdate_enderecoActionPerformed(evt);
               }
          });

          binserir_endereco.setText("Inserir");
          binserir_endereco.setToolTipText("Inserir endereço");
          binserir_endereco.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserir_enderecoActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout penderecoLayout = new javax.swing.GroupLayout(pendereco);
          pendereco.setLayout(penderecoLayout);
          penderecoLayout.setHorizontalGroup(
               penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(penderecoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addGroup(penderecoLayout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(binserir_endereco)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(bupdate_endereco)
                              .addGap(10, 10, 10)
                              .addComponent(bexcluir_endereco))
                         .addGroup(penderecoLayout.createSequentialGroup()
                              .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel15))
                              .addGap(18, 18, 18)
                              .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(tcep, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                   .addComponent(tbairro))
                              .addGap(18, 18, 18)
                              .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel13)
                                   .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(18, 18, 18)
                              .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(penderecoLayout.createSequentialGroup()
                                        .addComponent(trua, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                   .addGroup(penderecoLayout.createSequentialGroup()
                                        .addComponent(cestado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(66, 66, 66))
          );
          penderecoLayout.setVerticalGroup(
               penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(penderecoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel20)
                         .addComponent(tcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel13)
                         .addComponent(trua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel14)
                         .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel15)
                         .addComponent(tbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel19)
                         .addComponent(cestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel18)
                         .addComponent(tcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(penderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bexcluir_endereco)
                         .addComponent(bupdate_endereco)
                         .addComponent(binserir_endereco))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          bupdate.setText("update");
          bupdate.setToolTipText("update pessoa");
          bupdate.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bupdateActionPerformed(evt);
               }
          });

          bsair.setText("Sair");
          bsair.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bsairActionPerformed(evt);
               }
          });

          bexcluir.setText("Excluir");
          bexcluir.setToolTipText("Excluir pessoa");
          bexcluir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluirActionPerformed(evt);
               }
          });

          binserir.setText("Inserir");
          binserir.setToolTipText("Inserir pessoa");
          binserir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserirActionPerformed(evt);
               }
          });

          label_pessoa.setText("Tipo Pessoa");

          ctipopessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Fornecedor" }));
          ctipopessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
          ctipopessoa.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    ctipopessoaMouseClicked(evt);
               }
          });
          ctipopessoa.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ctipopessoaActionPerformed(evt);
               }
          });

          bimprimir.setText("Imprimir");
          bimprimir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bimprimirActionPerformed(evt);
               }
          });

          binserir_tipo.setText("+");
          binserir_tipo.setToolTipText("Inserir novos tipos de pessoa");
          binserir_tipo.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserir_tipoActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(pcontato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(pendereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bimprimir)
                    .addGap(18, 18, 18)
                    .addComponent(binserir)
                    .addGap(26, 26, 26)
                    .addComponent(bupdate)
                    .addGap(26, 26, 26)
                    .addComponent(bexcluir)
                    .addGap(28, 28, 28)
                    .addComponent(bsair)
                    .addGap(14, 14, 14))
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label_pessoa)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ctipopessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(binserir_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(label_pessoa)
                         .addComponent(ctipopessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(binserir_tipo))
                    .addGap(15, 15, 15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bupdate)
                         .addComponent(bsair)
                         .addComponent(bexcluir)
                         .addComponent(binserir)
                         .addComponent(bimprimir))
                    .addContainerGap(25, Short.MAX_VALUE))
          );

          jTabbedPane2.addTab("Cadastro", jPanel2);

          tabela_endereco.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          tabela_endereco.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabela_enderecoMouseClicked(evt);
               }
          });
          jScrollPane2.setViewportView(tabela_endereco);

          javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
          jPanel5.setLayout(jPanel5Layout);
          jPanel5Layout.setHorizontalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 744, Short.MAX_VALUE)
               .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                         .addContainerGap(19, Short.MAX_VALUE)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap()))
          );
          jPanel5Layout.setVerticalGroup(
               jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 423, Short.MAX_VALUE)
               .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          );

          jTabbedPane2.addTab("Endereços da pessoa", jPanel5);

          jLabel21.setText("Nome");

          tabela.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Código", "Nome", "CPF", "Telefone"
               }
          ));
          tabela.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelaMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tabela);

          bprocurar.setText("Procurar");
          bprocurar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bprocurarActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
          jPanel6.setLayout(jPanel6Layout);
          jPanel6Layout.setHorizontalGroup(
               jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane1)
                         .addGroup(jPanel6Layout.createSequentialGroup()
                              .addComponent(jLabel21)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(bprocurar)
                              .addGap(0, 9, Short.MAX_VALUE)))
                    .addContainerGap())
          );
          jPanel6Layout.setVerticalGroup(
               jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel21)
                         .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(bprocurar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addContainerGap())
          );

          jTabbedPane2.addTab("Procurar", jPanel6);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane2)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane2)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void tcpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tcpfFocusLost
          if(tcpf.getText() == null && tcpf.getText().isEmpty() || mas.valida_cpf(tcpf.getText()) == false){
               JOptionPane.showMessageDialog(null, "CPF inválido");
          }
     }//GEN-LAST:event_tcpfFocusLost

     private void tcpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcpfKeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_tcpfKeyTyped

     private void ttelefoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttelefoneKeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_ttelefoneKeyTyped

     private void tcelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcelularKeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_tcelularKeyTyped

     private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_jTextField4KeyTyped

     private void tcepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tcepFocusLost
          Cep           ser = new Cep();
          CepServiceVO  cep = ser.procuraCEP(tcep.getText());
          tcidade.setText(cep.getCidade());
          tbairro.setText(cep.getBairro());
          trua.setText(cep.getTipo_logradouro() + " " +cep.getLogradouro());
          if(cep.getUf().length() <= 3){
               estado = esrn.procuraSigla(cx, cep.getUf());
               cestado.setSelectedItem(estado.getNome());
          }
     }//GEN-LAST:event_tcepFocusLost

     private void tcepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcepKeyTyped
          mas.mascaraInteiro(evt);
     }//GEN-LAST:event_tcepKeyTyped

     private void bexcluir_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluir_enderecoActionPerformed
          if(pessoa != null && pessoa.getCodigo() != null){
               String msg      = "";
               int    response = JOptionPane.showConfirmDialog(null, "Tem certeza disso,\n"
                    + "Você quer excluir?", "Confirmação de excluir:",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               if (response == JOptionPane.YES_OPTION){
                    if(endereco != null && endereco.getCodigo() != null){
                         msg = ern.excluirEndereco(cx, endereco);
                    }else{
                         msg = "Para excluir escolha antes um endereço que tenha sido gravada no banco";
                    }
               }
               if(msg != null && !msg.isEmpty()){
                    JOptionPane.showMessageDialog(null, msg);
               }else{
                    obj_endereco.remove(endereco);
                    listar_endereco();
                    JOptionPane.showMessageDialog(null, "Excluido com sucesso");
               }
          }else{
               JOptionPane.showMessageDialog(null, "Primeiro deve ter uma pessoa no cadastro");
          }
     }//GEN-LAST:event_bexcluir_enderecoActionPerformed

     private void bupdate_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdate_enderecoActionPerformed
          if(pessoa != null && pessoa.getCodigo() != null){
               setaEndereco();
               String msg = ern.updateEndereco(cx, endereco);
               if(msg != null && !msg.isEmpty()){
                    JOptionPane.showMessageDialog(null, msg);
               }else{
                    for(int i = 0; i < obj_endereco.size(); i++){
                         if(obj_endereco.get(i).getCodigo() == endereco.getCodigo()){
                              obj_endereco.set(i, endereco);
                              listar_endereco();
                              break;
                         }
                    }
                    JOptionPane.showMessageDialog(null, "Atualizado com sucesso");
               }
          }else{
               JOptionPane.showMessageDialog(null, "Primeiro deve ter uma pessoa no cadastro");
          }
     }//GEN-LAST:event_bupdate_enderecoActionPerformed

     private void binserir_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserir_enderecoActionPerformed
          if(pessoa != null && pessoa.getCodigo() != null){
               endereco = new Endereco();
               setaEndereco();
               String msg = ern.inserirEndereco(cx, endereco);
               if(msg != null && !msg.isEmpty()){
                    JOptionPane.showMessageDialog(null, msg);
               }else{
                    obj_endereco.add(endereco);
                    listar_endereco();
                    JOptionPane.showMessageDialog(null, "Inserido com sucesso");
               }
          }else{
               JOptionPane.showMessageDialog(null, "Primeiro deve ter uma pessoa no cadastro");
          }
     }//GEN-LAST:event_binserir_enderecoActionPerformed

     private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
          setaPessoa();
          String msg = prn.updatePessoa(cx, pessoa);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               for(int i = 0; i < obj.size(); i++){
                    if(obj.get(i).getCodigo() == pessoa.getCodigo()){
                         obj.set(i, pessoa);
                         listar();
                         break;
                    }
               }
               JOptionPane.showMessageDialog(null, "Atualizado com sucesso");
          }
     }//GEN-LAST:event_bupdateActionPerformed

     private void bsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsairActionPerformed
          this.dispose();
     }//GEN-LAST:event_bsairActionPerformed

     private void bexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluirActionPerformed
          String msg      = "";
          int    response = JOptionPane.showConfirmDialog(null, "Tem certeza disso,\n"
               + "Você quer excluir?", "Confirmação de excluir:",
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if (response == JOptionPane.YES_OPTION){
               if(pessoa != null && pessoa.getCodigo() != null){
                    msg = prn.excluirPessoa(cx, pessoa);
               }else{
                    msg = "Para excluir escolha antes uma pessoa que tenha sido gravada no banco";
               }
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.remove(pessoa);
               listar();
               JOptionPane.showMessageDialog(null, "Excluido com sucesso");
          }
     }//GEN-LAST:event_bexcluirActionPerformed

     private void binserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserirActionPerformed
          pessoa = new Pessoa();
          setaPessoa();
          String msg = prn.inserirPessoa(cx, pessoa);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.add(pessoa);
               listar();
               JOptionPane.showMessageDialog(null, "Inserido com sucesso");
          }
     }//GEN-LAST:event_binserirActionPerformed

     private void bimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimirActionPerformed
          String msg = "";
          if(tcpf.getText() != null && !tcpf.getText().isEmpty()){
               try {
                    InputStream is = Relatorio.lerArquivoNet("/src/relatorios/pessoa/PerfilPessoa.jasper" );
                    if(is != null){
                         Map parametros  = new HashMap();
                         parametros.put( "cpf", this.tcpf.getText());
                         cx.conectar();
                         Connection   con         = cx.s.connection();
                         Relatorio.openReport(con, "Perfil Pessoa", parametros, is);
                         cx.desconectar();
                    }else{
                         JOptionPane.showMessageDialog(null, "Erro relatório não encontrado\n");
                    }
               } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(JFAvancadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
               }
          }else{
               msg = "Não pode gerar relatório sem CPF";
          }
          if(!msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }
     }//GEN-LAST:event_bimprimirActionPerformed

     private void tabela_enderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_enderecoMouseClicked
          endereco = obj_endereco.get(tabela_endereco.getSelectedRow());
          setaTelaEndereco();
     }//GEN-LAST:event_tabela_enderecoMouseClicked

     private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
          pessoa = obj.get(tabela.getSelectedRow());
          if(pessoa != null && pessoa.getNome() != null){
               setaTela();
          }
     }//GEN-LAST:event_tabelaMouseClicked

     private void bprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprocurarActionPerformed
          obj = prn.procuraNomeParcial(cx, tnomeproc.getText());
          if(obj != null && !obj.isEmpty()){
               listar();
          }else{
               JOptionPane.showMessageDialog(null, "Nada encontrado");
          }
     }//GEN-LAST:event_bprocurarActionPerformed

     private void binserir_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserir_tipoActionPerformed
          novotipo = true;
          new JFTipoPessoa(cx).setVisible(true);
     }//GEN-LAST:event_binserir_tipoActionPerformed

     private void jTabbedPane2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane2FocusGained
          if(novotipo == true){
               obj_tipo = new ArrayList();
               carregaTipoPessoa();
          }
     }//GEN-LAST:event_jTabbedPane2FocusGained

     private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          carregaTipoPessoa();
          carregaEstado();
     }//GEN-LAST:event_formWindowOpened

     private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
          if(novotipo == true){
               obj_tipo = new ArrayList();
               carregaTipoPessoa();
          }
     }//GEN-LAST:event_jPanel2FocusGained

     private void ctipopessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctipopessoaMouseClicked
          if(novotipo == true){
               obj_tipo = new ArrayList();
               carregaTipoPessoa();
               novotipo = false;
          }
     }//GEN-LAST:event_ctipopessoaMouseClicked

     private void ctipopessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctipopessoaActionPerformed
          if(obj_tipo != null && !obj_tipo.isEmpty() && ctipopessoa.getSelectedIndex() != -1){
               tipo = obj_tipo.get(ctipopessoa.getSelectedIndex());
               if(tipo.getNome().equalsIgnoreCase("FÁBRICA") || tipo.getNome().equalsIgnoreCase("JURIDICA")
               || tipo.getNome().equalsIgnoreCase("REPRESENTANTE") || tipo.getNome().equalsIgnoreCase("FORNECEDORES")){
                    jLabel6.setText("CNPJ");
                    jLabel7.setText("Insc. Est");
                    tcpf.removeAll();
                    //mudando o focus lost de cpf para um cnpj
                    FocusListener focusListener = new FocusListener() {
                      @Override
                      public void focusLost(FocusEvent e) {
                           if(mas.valida_cnpj(tcpf.getText()) == false){
                                JOptionPane.showMessageDialog(null, "Documento inválido");
                                tcpf.requestFocus();
                           }
                      }
                         @Override
                         public void focusGained(FocusEvent e) {
                              throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                         }
                    };                    
                    
                    tcpf.addFocusListener(focusListener);
                    tcpf.setToolTipText("Preencha aqui o CNPJ da empresa");
                    trg.setToolTipText("Preencha aqui a inscrição estadual");
                   
               }else{
                    jLabel6.setText("CPF");
                    jLabel7.setText("RG");
                    tcpf.removeAll();
                    //mudando o focus lost de cpf para um cnpj
                    FocusListener focusListener = new FocusListener() {
                      @Override
                      public void focusLost(FocusEvent e) {
                           if(mas.valida_cpf(tcpf.getText()) == false){
                                JOptionPane.showMessageDialog(null, "Documento inválido");
                                tcpf.requestFocus();
                           }
                      }
                         @Override
                         public void focusGained(FocusEvent e) {
                              
                         }
                    };                    
                    
                    tcpf.addFocusListener(focusListener);
                    tcpf.setToolTipText("Preencha aqui o CPF da empresa");
                    trg.setToolTipText("Preencha aqui o RG");            
               }
          }
     }//GEN-LAST:event_ctipopessoaActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(JFGerenciaPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFGerenciaPessoa().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton bupdate;
     private javax.swing.JButton bupdate_endereco;
     private javax.swing.JButton bexcluir;
     private javax.swing.JButton bexcluir_endereco;
     private javax.swing.JButton bimprimir;
     private javax.swing.JButton binserir;
     private javax.swing.JButton binserir_endereco;
     private javax.swing.JButton binserir_tipo;
     private javax.swing.JButton bprocurar;
     private javax.swing.JButton bsair;
     private javax.swing.JComboBox cestado;
     private javax.swing.JComboBox ctipopessoa;
     private com.toedter.calendar.JDateChooser dcnascimento;
     private javax.swing.JLabel jLabel10;
     private javax.swing.JLabel jLabel11;
     private javax.swing.JLabel jLabel12;
     private javax.swing.JLabel jLabel13;
     private javax.swing.JLabel jLabel14;
     private javax.swing.JLabel jLabel15;
     private javax.swing.JLabel jLabel16;
     private javax.swing.JLabel jLabel17;
     private javax.swing.JLabel jLabel18;
     private javax.swing.JLabel jLabel19;
     private javax.swing.JLabel jLabel20;
     private javax.swing.JLabel jLabel21;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JLabel jLabel6;
     private javax.swing.JLabel jLabel7;
     private javax.swing.JLabel jLabel8;
     private javax.swing.JLabel jLabel9;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel4;
     private javax.swing.JPanel jPanel5;
     private javax.swing.JPanel jPanel6;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JTabbedPane jTabbedPane2;
     private javax.swing.JTextField jTextField2;
     private javax.swing.JTextField jTextField4;
     private javax.swing.JLabel label_pessoa;
     private javax.swing.JPanel pcontato;
     private javax.swing.JPanel pendereco;
     private javax.swing.JTable tabela;
     private javax.swing.JTable tabela_endereco;
     private javax.swing.JTextField tbairro;
     private javax.swing.JTextField tcelular;
     private javax.swing.JTextField tcep;
     private javax.swing.JTextField tcidade;
     private javax.swing.JTextField tcpf;
     private javax.swing.JTextField temail;
     private javax.swing.JTextField tnome;
     private javax.swing.JTextField tnomeproc;
     private javax.swing.JTextField trg;
     private javax.swing.JTextField trua;
     private javax.swing.JPasswordField tsenha;
     private javax.swing.JTextField tsobrenome;
     private javax.swing.JTextField ttelefone;
     // End of variables declaration//GEN-END:variables

     /**seta informações da tela no objeto pessoa**/
     private void setaPessoa() {
          pessoa.setCpf(tcpf.getText());
          pessoa.setRg(trg.getText());
          pessoa.setEmail(temail.getText());
          pessoa.setNome(tnome.getText());
          pessoa.setSobrenome(tsobrenome.getText());
          pessoa.setTelefone(ttelefone.getText());
          pessoa.setTelefone2(tcelular.getText());
          pessoa.setTipo(tipo);
          pessoa.setNascimento(dcnascimento.getDate());
          pessoa.setSenha(tsenha.getText());
          setaEndereco();
     }
     
     /**seta informações do objeto pessoa na tela**/
     private void setaTela() {
          tcpf.setText(pessoa.getCpf());
          temail.setText(pessoa.getEmail());
          tnome.setText(pessoa.getNome());
          tsobrenome.setText(pessoa.getSobrenome());
          ttelefone.setText(pessoa.getTelefone());
          tcelular.setText(pessoa.getTelefone2());
          ctipopessoa.setSelectedItem(pessoa.getTipo().getNome());
          dcnascimento.setDate(pessoa.getNascimento());
          tsenha.setText(pessoa.getSenha());
          obj_endereco = ern.procuraCodPessoa(cx, pessoa.getCodigo());
          listar_endereco();
     }     

   /**lista tudo o que está na tabela**/  
    private void listar() {
            tabela.setModel(new TableModel(titulo, obj.size(), titulo.length));
            for(int i = 0; i < obj.size(); i++){
                    tabela.setValueAt(obj.get(i).getCodigo(), i, 0);
                    tabela.setValueAt(obj.get(i).getNome().toUpperCase() + " " + obj.get(i).getSobrenome().toUpperCase(), i, 1);
                    tabela.setValueAt(obj.get(i).getCpf(), i, 2);
                    tabela.setValueAt(obj.get(i).getTelefone(), i, 3);
            }
            tabela.setAutoCreateRowSorter(true);    
    }  

     private void listar_endereco() {
            tabela_endereco.setModel(new TableModel(titulo_endereco, obj_endereco.size(), titulo_endereco.length));
            for(int i = 0; i < obj_endereco.size(); i++){
                    tabela_endereco.setValueAt(obj_endereco.get(i).getCodigo(), i, 0);
                    tabela_endereco.setValueAt(obj_endereco.get(i).getCep(), i, 1);
                    tabela_endereco.setValueAt(obj_endereco.get(i).getEndereco().toUpperCase(), i, 2);
                    tabela_endereco.setValueAt(obj_endereco.get(i).getEstado().getNome().toUpperCase(), i, 3);
            }
            tabela_endereco.setAutoCreateRowSorter(true); 
     }

     private void setaEndereco() {
          endereco.setPessoa(pessoa);
          endereco.setCep(tcep.getText());
          endereco.setEndereco(trua.getText());
          endereco.setEstado(estado); 
          endereco.setBairro(tbairro.getText().toUpperCase());
          endereco.setCidade(tcidade.getText().toUpperCase());
     }
     
     public void setaTelaEndereco(){
          tcep.setText(endereco.getCep().toUpperCase());
          trua.setText(endereco.getEndereco().toUpperCase());
          cestado.setSelectedItem(endereco.getEstado().getNome().toUpperCase());
          tcidade.setText(endereco.getCidade().toUpperCase());
          tbairro.setText(endereco.getBairro().toUpperCase());
     }

     private void carregaTipoPessoa() {
          if(obj_tipo == null || obj_tipo.isEmpty()){
               obj_tipo = trn.procuraTodos(cx);
               if(obj_tipo != null && !obj_tipo.isEmpty()){
                    ctipopessoa.removeAllItems();
                    for (TipoPessoa tp : obj_tipo) {
                         ctipopessoa.addItem(tp.getNome().toUpperCase());
                    }
               }
          }
     }

     private void carregaEstado() {
          if(obj_estado == null || obj_estado.isEmpty()){
               obj_estado = esrn.procuraTodos(cx);
               if(obj_estado != null && !obj_estado.isEmpty()){
                    cestado.removeAllItems();
                    for (Estado e : obj_estado) {
                         cestado.addItem(e.getNome().toUpperCase());
                    }                    
               }
          }
     }
    

    
}
