/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;
import negocio.UsuarioRN;
import persistencia.Conexao;
import vo.Usuario;

/**
 *
 * @author ThyagoHenrique
 */
public class JFLogin extends javax.swing.JFrame {

     UsuarioRN urn            = new UsuarioRN();
     Usuario   usuario        = new Usuario();
     Conexao   cx             = new Conexao();
     /**
      * Creates new form JFLogin
      */
     public JFLogin() {
          initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          tlogin = new javax.swing.JTextField();
          tsenha = new javax.swing.JPasswordField();
          bsair = new javax.swing.JButton();
          bentrar = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Login no sistema");

          jLabel1.setText("Usuário");

          jLabel2.setText("Senha");

          tsenha.addKeyListener(new java.awt.event.KeyAdapter() {
               public void keyPressed(java.awt.event.KeyEvent evt) {
                    tsenhaKeyPressed(evt);
               }
          });

          bsair.setText("Sair");
          bsair.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bsairActionPerformed(evt);
               }
          });

          bentrar.setText("Entrar");
          bentrar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bentrarActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addGap(19, 19, 19)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel1)
                                   .addComponent(jLabel2))
                              .addGap(18, 18, 18)
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(tlogin)
                                   .addComponent(tsenha)))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addContainerGap(140, Short.MAX_VALUE)
                              .addComponent(bentrar)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(bsair)))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(tlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(tsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bsair)
                         .addComponent(bentrar))
                    .addGap(29, 29, 29))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void bentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bentrarActionPerformed
          entrar();
     }//GEN-LAST:event_bentrarActionPerformed

     private void bsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsairActionPerformed
          dispose();
     }//GEN-LAST:event_bsairActionPerformed

     private void tsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsenhaKeyPressed
          if(evt.getKeyCode() == 10){
               entrar();
          }
     }//GEN-LAST:event_tsenhaKeyPressed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (Exception ex) {
               java.util.logging.Logger.getLogger(JFAvancadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFLogin().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton bentrar;
     private javax.swing.JButton bsair;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JTextField tlogin;
     private javax.swing.JPasswordField tsenha;
     // End of variables declaration//GEN-END:variables

     private void entrar() {
          String msg;
          try{
               msg = cx.conectarBanco();
               if(msg == null || msg.isEmpty()){
                    if(tlogin.getText() != null && !tlogin.getText().isEmpty() && tsenha.getText() != null && !tsenha.getText().isEmpty()){
                         usuario = urn.verificarLogin(cx, tlogin.getText(), tsenha.getText());
                         if(usuario != null && usuario.getCodigo() != null){
                              this.dispose();
                              new JFPrincipal(cx, usuario).setVisible(true);
                         }else{
                              msg = "Login ou senha errados, tente novamente";
                         }
                    }else{
                         msg = "Preencha login e senha para entrar";
                    }
               }
          }catch(Exception ex){
              msg = "Erro ao conectar o programa ocasionado por:\n" + ex; 
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }
     }
}
