/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.PaisRN;
import negocio.RegiaoRN;
import persistencia.Conexao;
import recursos.utilitarios.TableModel;
import vo.Pais;
import vo.Regiao;

/**
 *
 * @author ThyagoHenrique
 */
public class JFPais extends javax.swing.JFrame {
     String         titulo[]            = new String[]{"Código", "Nome", "Sigla"};
     TableModel     tm                  = new TableModel(titulo, 1, titulo.length);         
     List<Pais>     obj                 = new ArrayList();
     Pais           pais                = new Pais();
     PaisRN         prn                 = new PaisRN();
     RegiaoRN       rern                = new RegiaoRN();
     Regiao         regiao              = new Regiao();
     List<Regiao>   obj_regiao          = new ArrayList();
     Conexao        cx;
     private boolean novaregiao         = false;
     /**
      * Creates new form JFPais
      */
     public JFPais() {
          initComponents();
     }


     public JFPais(Conexao cx) {
          initComponents();
          this.cx = cx;
          tabela.setModel(tm);
     }       
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTabbedPane1 = new javax.swing.JTabbedPane();
          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          tnome = new javax.swing.JTextField();
          bsair = new javax.swing.JButton();
          bexcluir = new javax.swing.JButton();
          bupdate = new javax.swing.JButton();
          binserir = new javax.swing.JButton();
          jLabel3 = new javax.swing.JLabel();
          tsigla = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          cregiao = new javax.swing.JComboBox();
          badicionar_regiao = new javax.swing.JButton();
          jPanel2 = new javax.swing.JPanel();
          jLabel2 = new javax.swing.JLabel();
          tnomeproc = new javax.swing.JTextField();
          bprocurar = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          tabela = new javax.swing.JTable();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Países atendidos");

          jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
               public void focusGained(java.awt.event.FocusEvent evt) {
                    jTabbedPane1FocusGained(evt);
               }
          });

          jLabel1.setText("Nome");

          bsair.setText("Sair");
          bsair.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bsairActionPerformed(evt);
               }
          });

          bexcluir.setText("Excluir");
          bexcluir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluirActionPerformed(evt);
               }
          });

          bupdate.setText("update");
          bupdate.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bupdateActionPerformed(evt);
               }
          });

          binserir.setText("Inserir");
          binserir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserirActionPerformed(evt);
               }
          });

          jLabel3.setText("Sigla");

          jLabel4.setText("Região");

          cregiao.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cregiaoMouseClicked(evt);
               }
          });
          cregiao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cregiaoActionPerformed(evt);
               }
          });

          badicionar_regiao.setText("+");
          badicionar_regiao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    badicionar_regiaoActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(63, Short.MAX_VALUE)
                    .addComponent(binserir)
                    .addGap(18, 18, 18)
                    .addComponent(bupdate)
                    .addGap(18, 18, 18)
                    .addComponent(bexcluir)
                    .addGap(18, 18, 18)
                    .addComponent(bsair)
                    .addGap(32, 32, 32))
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel1)
                                   .addComponent(jLabel3))
                              .addGap(24, 24, 24)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(tsigla, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addGap(18, 18, 18)
                              .addComponent(cregiao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(26, 26, 26)
                              .addComponent(badicionar_regiao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(cregiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(badicionar_regiao))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(tsigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bsair)
                         .addComponent(bexcluir)
                         .addComponent(bupdate)
                         .addComponent(binserir))
                    .addContainerGap(102, Short.MAX_VALUE))
          );

          jTabbedPane1.addTab("Cadastro", jPanel1);

          jLabel2.setText("Nome");

          bprocurar.setText("Procurar");
          bprocurar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bprocurarActionPerformed(evt);
               }
          });

          tabela.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null},
                    {null, null},
                    {null, null},
                    {null, null}
               },
               new String [] {
                    "Código", "Nome"
               }
          ));
          tabela.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelaMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tabela);

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(bprocurar)
                              .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(bprocurar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addContainerGap())
          );

          jTabbedPane1.addTab("Procurar", jPanel2);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane1)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane1)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void bsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsairActionPerformed
          this.dispose();
     }//GEN-LAST:event_bsairActionPerformed

     private void bexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluirActionPerformed
          String msg      = "";
          int    response = JOptionPane.showConfirmDialog(null, "Tem certeza disso,\n"
               + "Você quer excluir?", "Confirmação de excluir:",
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if (response == JOptionPane.YES_OPTION) {
               if(pais != null && pais.getCodigo() != null){
                    msg = prn.excluirPais(cx, pais);
               }
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.remove(pais);
               listar();
               JOptionPane.showMessageDialog(null, "Excluido com sucesso");
          }
     }//GEN-LAST:event_bexcluirActionPerformed

     private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
          setaPais();
          String msg = prn.updatePais(cx, pais);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               for(int i = 0; i < obj.size(); i++){
                    if(obj.get(i).getCodigo() == pais.getCodigo()){
                         obj.set(i, pais);
                         listar();
                         break;
                    }
               }
               JOptionPane.showMessageDialog(null, "Atualizado com sucesso");
          }
     }//GEN-LAST:event_bupdateActionPerformed

     private void binserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserirActionPerformed
          pais = new Pais();
          setaPais();
          String msg = prn.inserirPais(cx, pais);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.add(pais);
               listar();
               JOptionPane.showMessageDialog(null, "Inserido com sucesso");
          }
     }//GEN-LAST:event_binserirActionPerformed

     private void cregiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cregiaoActionPerformed
          if(obj_regiao != null && !obj_regiao.isEmpty() && cregiao.getSelectedIndex() != -1){
               regiao = obj_regiao.get(cregiao.getSelectedIndex());
          }
     }//GEN-LAST:event_cregiaoActionPerformed

     private void bprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprocurarActionPerformed
          obj = prn.procuraNomeParcial(cx, tnomeproc.getText());
          if(obj != null && !obj.isEmpty()){
               listar();
          }else{
               JOptionPane.showMessageDialog(null, "Nada encontrado");
          }
     }//GEN-LAST:event_bprocurarActionPerformed

     private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
          pais = obj.get(tabela.getSelectedRow());
          setaTelaPais();
     }//GEN-LAST:event_tabelaMouseClicked

     private void badicionar_regiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badicionar_regiaoActionPerformed
          novaregiao = true;
          new JFRegiao(cx).setVisible(true);
     }//GEN-LAST:event_badicionar_regiaoActionPerformed

     private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
          if(novaregiao == true){
               carregaRegiao();
          }
     }//GEN-LAST:event_jTabbedPane1FocusGained

     private void cregiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cregiaoMouseClicked
          if(novaregiao == true){
               carregaRegiao();
               novaregiao = false;
          }
     }//GEN-LAST:event_cregiaoMouseClicked

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (Exception ex) {
               java.util.logging.Logger.getLogger(JFAvancadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFPais().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton badicionar_regiao;
     private javax.swing.JButton bupdate;
     private javax.swing.JButton bexcluir;
     private javax.swing.JButton binserir;
     private javax.swing.JButton bprocurar;
     private javax.swing.JButton bsair;
     private javax.swing.JComboBox cregiao;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JTable tabela;
     private javax.swing.JTextField tnome;
     private javax.swing.JTextField tnomeproc;
     private javax.swing.JTextField tsigla;
     // End of variables declaration//GEN-END:variables

    private void listar() {
            tabela.setModel(new TableModel(titulo, obj.size(), titulo.length));
            for(int i=0; i < obj.size(); i++){
                    tabela.setValueAt(obj.get(i).getCodigo(), i, 0);
                    tabela.setValueAt(obj.get(i).getNome().toUpperCase(), i, 1);
                    tabela.setValueAt(obj.get(i).getSigla().toUpperCase(), i, 2);
            }
            tabela.setAutoCreateRowSorter(true);    
    }  

     private void setaTelaPais() {
          tnome.setText(pais.getNome().toUpperCase());
          tsigla.setText(pais.getSigla().toUpperCase());
          cregiao.setSelectedItem(pais.getRegiao().getNome().toUpperCase());
     }

     private void setaPais() {
          pais.setNome(tnome.getText().toUpperCase());
          pais.setSigla(tsigla.getText().toUpperCase());
          pais.setRegiao(regiao);
     }

     private void carregaRegiao() {
          obj_regiao = rern.procuraTodos(cx);
          if(obj_regiao != null && !obj_regiao.isEmpty()){
               cregiao.removeAllItems();
               for(Regiao r : obj_regiao){
                    cregiao.addItem(r.getNome().toUpperCase());
               }
          }
     }
}
