/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import negocio.ContaRN;
import negocio.VendaRN;
import persistencia.Conexao;
import recursos.utilitarios.Mascara;
import recursos.utilitarios.Relatorio;
import recursos.utilitarios.Tempo;
import vo.Conta;
import vo.Usuario;
import vo.Venda;

/**
 *
 * @author ThyagoHenrique
 */
public class JFPrincipal extends javax.swing.JFrame {

     Tempo               tempo          = new Tempo();
     VendaRN             vrn            = new VendaRN();
     String              data           = "";
     Toolkit             tk             = Toolkit.getDefaultToolkit();  
     Dimension           screenSize     = tk.getScreenSize();  
     int                 screenHeight   = screenSize.height;  
     int                 screenWidth    = screenSize.width;     
     JFVenda             jfvenda;
     Conexao             cx;
     Usuario             usuario        = new Usuario();
     /**
      * Creates new form JFPrincipal
      */
     public JFPrincipal(Conexao cx, Usuario usuario) {
          initComponents();
          String msg = "";
          try{
               this.cx        = cx;  
               this.usuario   = usuario;
               this.setExtendedState(Frame.MAXIMIZED_BOTH);
               tempo.le_data();
               data = (tempo.dia + "/" + tempo.mes + "/" + tempo.ano);
               ldata.setText(data);
               timer1.start();
               this.conectar();
          }catch(Exception ex){
               msg = "Erro ao iniciar aplicativo causado por:\n" + ex;
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }
     }     
     
     public JFPrincipal() {
          initComponents();
          String msg;
          try{
               cx  = new Conexao();
               msg = cx.conectarBanco();    
               if(msg == null || msg.isEmpty()){
                    this.setExtendedState(Frame.MAXIMIZED_BOTH);
                    tempo.le_data();
                    data = (tempo.dia + "/" + tempo.mes + "/" + tempo.ano);
                    ldata.setText(data);
                    timer1.start();
                    this.conectar();
                    jfvenda = new JFVenda(cx);
                    centralizaJanela(jfvenda);
                    jfvenda.setVisible(true);
               }
          }catch(Exception ex){
               msg = "Erro ao iniciar aplicativo causado por:\n" + ex;
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jSeparator1 = new javax.swing.JSeparator();
        dpprincipal = new javax.swing.JDesktopPane();
        pinformacoes_financeiras = new javax.swing.JPanel();
        lvendas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lconta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lvendasicompletas = new javax.swing.JLabel();
        pinformacoes_sistema = new javax.swing.JPanel();
        lhora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ldata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lestado = new javax.swing.JLabel();
        pfinanceiro = new javax.swing.JPanel();
        lfinanceiro_logo = new javax.swing.JLabel();
        lcompra2 = new javax.swing.JLabel();
        lcompra1 = new javax.swing.JLabel();
        lvenda2 = new javax.swing.JLabel();
        lvenda1 = new javax.swing.JLabel();
        lconta2 = new javax.swing.JLabel();
        lconta1 = new javax.swing.JLabel();
        ppessoa = new javax.swing.JPanel();
        lpessoa_logo = new javax.swing.JLabel();
        lpessoa1 = new javax.swing.JLabel();
        ltipopessoa1 = new javax.swing.JLabel();
        ltipopessoa2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lvendedor = new javax.swing.JLabel();
        lusuario = new javax.swing.JLabel();
        pproduto = new javax.swing.JPanel();
        lproduto_logo = new javax.swing.JLabel();
        lproduto1 = new javax.swing.JLabel();
        lcategoriaproduto = new javax.swing.JLabel();
        lvariacao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prelatorio = new javax.swing.JPanel();
        lrelatorios = new javax.swing.JLabel();
        lrelatorio_venda1 = new javax.swing.JLabel();
        lrelatorio_venda2 = new javax.swing.JLabel();
        lrelatorio_produto = new javax.swing.JLabel();
        lrelatorio_logo = new javax.swing.JLabel();
        lrelatorio_contap = new javax.swing.JLabel();
        lrelatorio_cliente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lfuncionario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        misair = new javax.swing.JMenuItem();
        jmsite = new javax.swing.JMenu();
        miavancadas = new javax.swing.JMenuItem();
        miestado = new javax.swing.JMenuItem();
        miformapagamento = new javax.swing.JMenuItem();
        mipais = new javax.swing.JMenuItem();
        miregiao = new javax.swing.JMenuItem();
        mipagina = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        micompra = new javax.swing.JMenuItem();
        mivenda = new javax.swing.JMenuItem();
        miconta = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mipessoa = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mitipopessoa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        migerenciaproduto = new javax.swing.JMenuItem();
        micatproduto = new javax.swing.JMenuItem();
        mivariacao = new javax.swing.JMenuItem();
        mirelatorios = new javax.swing.JMenu();
        mivendas_incompletas = new javax.swing.JMenuItem();
        mivendas_completas = new javax.swing.JMenuItem();
        miprodutos_cadastrados = new javax.swing.JMenuItem();

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Janela Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        dpprincipal.setBackground(new java.awt.Color(204, 204, 204));
        dpprincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dpprincipal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dpprincipalMouseMoved(evt);
            }
        });

        pinformacoes_financeiras.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações financeiras"));

        lvendas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvendas.setForeground(new java.awt.Color(0, 51, 153));
        lvendas.setText("total em vendas");
        lvendas.setToolTipText("vendas completas realizadas");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Vendas completas");

        lconta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lconta.setForeground(new java.awt.Color(0, 51, 153));
        lconta.setText("total em atraso");
        lconta.setToolTipText("Contas em atraso");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Contas em atraso");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Vendas incompletas");

        lvendasicompletas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvendasicompletas.setForeground(new java.awt.Color(0, 51, 153));
        lvendasicompletas.setText("total em vendas");
        lvendasicompletas.setToolTipText("Vendas incompletas");

        javax.swing.GroupLayout pinformacoes_financeirasLayout = new javax.swing.GroupLayout(pinformacoes_financeiras);
        pinformacoes_financeiras.setLayout(pinformacoes_financeirasLayout);
        pinformacoes_financeirasLayout.setHorizontalGroup(
            pinformacoes_financeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinformacoes_financeirasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinformacoes_financeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinformacoes_financeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lvendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lvendasicompletas, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(lconta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pinformacoes_financeirasLayout.setVerticalGroup(
            pinformacoes_financeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinformacoes_financeirasLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pinformacoes_financeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lconta)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinformacoes_financeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvendas)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pinformacoes_financeirasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lvendasicompletas))
                .addGap(23, 23, 23))
        );

        pinformacoes_financeiras.setBounds(480, 240, 380, 90);
        dpprincipal.add(pinformacoes_financeiras, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pinformacoes_sistema.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informações do sistema"));

        lhora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lhora.setForeground(new java.awt.Color(0, 51, 153));
        lhora.setText("hora do sistema");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hora");

        ldata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ldata.setForeground(new java.awt.Color(0, 51, 153));
        ldata.setText("data do sistema");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Data");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Estado");

        lestado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lestado.setForeground(new java.awt.Color(0, 51, 153));
        lestado.setText("estado programa");

        javax.swing.GroupLayout pinformacoes_sistemaLayout = new javax.swing.GroupLayout(pinformacoes_sistema);
        pinformacoes_sistema.setLayout(pinformacoes_sistemaLayout);
        pinformacoes_sistemaLayout.setHorizontalGroup(
            pinformacoes_sistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinformacoes_sistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinformacoes_sistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(pinformacoes_sistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lestado, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(ldata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pinformacoes_sistemaLayout.setVerticalGroup(
            pinformacoes_sistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinformacoes_sistemaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pinformacoes_sistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldata)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinformacoes_sistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lhora)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pinformacoes_sistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lestado))
                .addContainerGap())
        );

        pinformacoes_sistema.setBounds(480, 340, 230, 90);
        dpprincipal.add(pinformacoes_sistema, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pfinanceiro.setBackground(new java.awt.Color(233, 235, 238));
        pfinanceiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lfinanceiro_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/financeiro.jpg"))); // NOI18N

        lcompra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/comprar.jpg"))); // NOI18N
        lcompra2.setToolTipText("Gerencia Comprar");
        lcompra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcompra2MouseClicked(evt);
            }
        });
        lcompra2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lcompra1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lcompra1.setForeground(new java.awt.Color(0, 51, 153));
        lcompra1.setText("Gerencia Compras");
        lcompra1.setToolTipText("Gerencia Comprar");
        lcompra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcompra1MouseClicked(evt);
            }
        });
        lcompra1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lvenda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/venda.jpg"))); // NOI18N
        lvenda2.setToolTipText("Gerencia Venda");
        lvenda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvenda2MouseClicked(evt);
            }
        });
        lvenda2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lvenda1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvenda1.setForeground(new java.awt.Color(0, 51, 153));
        lvenda1.setText("Gerencia Venda");
        lvenda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvenda1MouseClicked(evt);
            }
        });
        lvenda1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lconta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/conta.jpg"))); // NOI18N
        lconta2.setToolTipText("Gerencia Conta");
        lconta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lconta2MouseClicked(evt);
            }
        });
        lconta2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lconta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lconta1.setForeground(new java.awt.Color(0, 51, 153));
        lconta1.setText("Gerencia Conta");
        lconta1.setToolTipText("Gerencia Conta");
        lconta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lconta1MouseClicked(evt);
            }
        });
        lconta1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout pfinanceiroLayout = new javax.swing.GroupLayout(pfinanceiro);
        pfinanceiro.setLayout(pfinanceiroLayout);
        pfinanceiroLayout.setHorizontalGroup(
            pfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfinanceiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lvenda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lcompra2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                    .addComponent(lconta2))
                .addGap(37, 37, 37)
                .addGroup(pfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lvenda1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lcompra1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(lconta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addComponent(lfinanceiro_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pfinanceiroLayout.setVerticalGroup(
            pfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pfinanceiroLayout.createSequentialGroup()
                .addComponent(lfinanceiro_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lcompra2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lcompra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lvenda2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvenda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pfinanceiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pfinanceiroLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(lconta2))
                    .addComponent(lconta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pfinanceiro.setBounds(180, 20, 280, 200);
        dpprincipal.add(pfinanceiro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ppessoa.setBackground(new java.awt.Color(233, 235, 238));
        ppessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lpessoa_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/pessoa.jpg"))); // NOI18N

        lpessoa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lpessoa1.setForeground(new java.awt.Color(0, 51, 153));
        lpessoa1.setText("Gerencia Pessoa");
        lpessoa1.setToolTipText("Gerencia Pessoa");
        lpessoa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpessoa1MouseClicked(evt);
            }
        });
        lpessoa1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        ltipopessoa1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ltipopessoa1.setForeground(new java.awt.Color(0, 51, 153));
        ltipopessoa1.setText("Tipo de Pessoa");
        ltipopessoa1.setToolTipText("Gerencia Tipo Pessoa");
        ltipopessoa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltipopessoa1MouseClicked(evt);
            }
        });
        ltipopessoa1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        ltipopessoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/tipopessoa.jpg"))); // NOI18N
        ltipopessoa2.setToolTipText("Gerencia Tipo Pessoa");
        ltipopessoa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltipopessoa2MouseClicked(evt);
            }
        });
        ltipopessoa2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/pessoa1.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lvendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvendedor.setForeground(new java.awt.Color(0, 51, 153));
        lvendedor.setText("Gerencia Vendedor");
        lvendedor.setToolTipText("Gerencia Tipo Pessoa");
        lvendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvendedorMouseClicked(evt);
            }
        });
        lvendedor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lusuario.setForeground(new java.awt.Color(0, 51, 153));
        lusuario.setText("Gerencia Usuário");
        lusuario.setToolTipText("Gerencia Tipo Pessoa");
        lusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lusuarioMouseClicked(evt);
            }
        });
        lusuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout ppessoaLayout = new javax.swing.GroupLayout(ppessoa);
        ppessoa.setLayout(ppessoaLayout);
        ppessoaLayout.setHorizontalGroup(
            ppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppessoaLayout.createSequentialGroup()
                .addGroup(ppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ppessoaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ltipopessoa2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(ppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lpessoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ltipopessoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lvendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addComponent(lpessoa_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );
        ppessoaLayout.setVerticalGroup(
            ppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ppessoaLayout.createSequentialGroup()
                .addComponent(lpessoa_logo)
                .addGap(16, 16, 16)
                .addGroup(ppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lpessoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ppessoaLayout.createSequentialGroup()
                        .addComponent(ltipopessoa2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppessoaLayout.createSequentialGroup()
                        .addComponent(ltipopessoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lvendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addComponent(lusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ppessoa.setBounds(470, 20, 280, 200);
        dpprincipal.add(ppessoa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pproduto.setBackground(new java.awt.Color(233, 235, 238));
        pproduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lproduto_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/produtos.jpg"))); // NOI18N

        lproduto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lproduto1.setForeground(new java.awt.Color(0, 51, 153));
        lproduto1.setText("Gerencia Produto");
        lproduto1.setToolTipText("Gerencia Produto");
        lproduto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lproduto1MouseClicked(evt);
            }
        });
        lproduto1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lcategoriaproduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lcategoriaproduto.setForeground(new java.awt.Color(0, 51, 153));
        lcategoriaproduto.setText("Categoria Produto");
        lcategoriaproduto.setToolTipText("");
        lcategoriaproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcategoriaprodutoMouseClicked(evt);
            }
        });
        lcategoriaproduto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lvariacao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lvariacao.setForeground(new java.awt.Color(0, 51, 153));
        lvariacao.setText("Variações");
        lvariacao.setToolTipText("");
        lvariacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvariacaoMouseClicked(evt);
            }
        });
        lvariacao.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/produtos1.jpg"))); // NOI18N

        javax.swing.GroupLayout pprodutoLayout = new javax.swing.GroupLayout(pproduto);
        pproduto.setLayout(pprodutoLayout);
        pprodutoLayout.setHorizontalGroup(
            pprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pprodutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lcategoriaproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lproduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvariacao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addComponent(lproduto_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pprodutoLayout.setVerticalGroup(
            pprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pprodutoLayout.createSequentialGroup()
                .addComponent(lproduto_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pprodutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pprodutoLayout.createSequentialGroup()
                        .addComponent(lproduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lcategoriaproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lvariacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pprodutoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pproduto.setBounds(760, 20, 280, 200);
        dpprincipal.add(pproduto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        prelatorio.setBackground(new java.awt.Color(233, 235, 238));
        prelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lrelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/relatorios1.jpg"))); // NOI18N

        lrelatorio_venda1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lrelatorio_venda1.setForeground(new java.awt.Color(0, 51, 153));
        lrelatorio_venda1.setText("Vendas completas");
        lrelatorio_venda1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lrelatorio_venda1MouseClicked(evt);
            }
        });
        lrelatorio_venda1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lrelatorio_venda2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lrelatorio_venda2.setForeground(new java.awt.Color(0, 51, 153));
        lrelatorio_venda2.setText("Vendas incompletas");
        lrelatorio_venda2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lrelatorio_venda2MouseClicked(evt);
            }
        });
        lrelatorio_venda2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lrelatorio_produto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lrelatorio_produto.setForeground(new java.awt.Color(0, 51, 153));
        lrelatorio_produto.setText("Produtos cadastrados");
        lrelatorio_produto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lrelatorio_produtoMouseClicked(evt);
            }
        });
        lrelatorio_produto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lrelatorio_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/relatorios.jpg"))); // NOI18N

        lrelatorio_contap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lrelatorio_contap.setForeground(new java.awt.Color(0, 51, 153));
        lrelatorio_contap.setText("Contas à pagar");
        lrelatorio_contap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lrelatorio_contapMouseClicked(evt);
            }
        });
        lrelatorio_contap.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        lrelatorio_cliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lrelatorio_cliente.setForeground(new java.awt.Color(0, 51, 153));
        lrelatorio_cliente.setText("Clientes cadastrados");
        lrelatorio_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lrelatorio_clienteMouseClicked(evt);
            }
        });
        lrelatorio_cliente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelsMouseMoved(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagens/relatorios1.jpg"))); // NOI18N

        javax.swing.GroupLayout prelatorioLayout = new javax.swing.GroupLayout(prelatorio);
        prelatorio.setLayout(prelatorioLayout);
        prelatorioLayout.setHorizontalGroup(
            prelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prelatorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lrelatorios)
                    .addComponent(jLabel8))
                .addGroup(prelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prelatorioLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lrelatorio_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(prelatorioLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(prelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lrelatorio_produto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lrelatorio_venda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lrelatorio_venda1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lrelatorio_contap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42))))
            .addGroup(prelatorioLayout.createSequentialGroup()
                .addComponent(lrelatorio_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        prelatorioLayout.setVerticalGroup(
            prelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prelatorioLayout.createSequentialGroup()
                .addComponent(lrelatorio_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(prelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prelatorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lrelatorios)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prelatorioLayout.createSequentialGroup()
                        .addGroup(prelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(prelatorioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(99, 99, 99))
                            .addGroup(prelatorioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lrelatorio_venda1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lrelatorio_venda2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lrelatorio_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lrelatorio_contap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lrelatorio_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        prelatorio.setBounds(180, 230, 280, 200);
        dpprincipal.add(prelatorio, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lfuncionario.setText("Funcionário");
        lfuncionario.setBounds(190, 440, 600, 14);
        dpprincipal.add(lfuncionario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu2.setText("Ajuda");

        misair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        misair.setText("Sair");
        misair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misairActionPerformed(evt);
            }
        });
        jMenu2.add(misair);

        jMenuBar1.add(jMenu2);

        jmsite.setText("Configurações");

        miavancadas.setText("Avançadas");
        miavancadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miavancadasActionPerformed(evt);
            }
        });
        jmsite.add(miavancadas);

        miestado.setText("Estado");
        miestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miestadoActionPerformed(evt);
            }
        });
        jmsite.add(miestado);

        miformapagamento.setText("Forma Pag.");
        miformapagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miformapagamentoActionPerformed(evt);
            }
        });
        jmsite.add(miformapagamento);

        mipais.setText("País");
        mipais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mipaisActionPerformed(evt);
            }
        });
        jmsite.add(mipais);

        miregiao.setText("Região");
        miregiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miregiaoActionPerformed(evt);
            }
        });
        jmsite.add(miregiao);

        mipagina.setText("Página");
        mipagina.setToolTipText("Gerencia Páginas adicionadas ao site");
        mipagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mipaginaActionPerformed(evt);
            }
        });
        jmsite.add(mipagina);

        jMenuBar1.add(jmsite);

        jMenu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu4.setText("Financeiro");

        micompra.setText("Ger. Compra");
        micompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micompraActionPerformed(evt);
            }
        });
        jMenu4.add(micompra);

        mivenda.setText("Ger. Venda");
        mivenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivendaActionPerformed(evt);
            }
        });
        jMenu4.add(mivenda);

        miconta.setText("Ger. Conta");
        miconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micontaActionPerformed(evt);
            }
        });
        jMenu4.add(miconta);

        jMenuBar1.add(jMenu4);

        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setText("Pessoa");

        mipessoa.setText("Ger. Pessoa");
        mipessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mipessoaActionPerformed(evt);
            }
        });
        jMenu1.add(mipessoa);

        jMenuItem1.setText("Ger. Vendedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ger. Usuário");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mitipopessoa.setText("Tipo Pessoa");
        mitipopessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitipopessoaActionPerformed(evt);
            }
        });
        jMenu1.add(mitipopessoa);

        jMenuBar1.add(jMenu1);

        jMenu3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu3.setText("Produto");

        migerenciaproduto.setText("Ger. Produto");
        migerenciaproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                migerenciaprodutoActionPerformed(evt);
            }
        });
        jMenu3.add(migerenciaproduto);

        micatproduto.setText("Cat. Produto");
        micatproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                micatprodutoActionPerformed(evt);
            }
        });
        jMenu3.add(micatproduto);

        mivariacao.setText("Variações");
        mivariacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivariacaoActionPerformed(evt);
            }
        });
        jMenu3.add(mivariacao);

        jMenuBar1.add(jMenu3);

        mirelatorios.setText("Relatórios");

        mivendas_incompletas.setText("Vendas Incompletas");
        mivendas_incompletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivendas_incompletasActionPerformed(evt);
            }
        });
        mirelatorios.add(mivendas_incompletas);

        mivendas_completas.setText("Vendas Completas");
        mivendas_completas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mivendas_completasActionPerformed(evt);
            }
        });
        mirelatorios.add(mivendas_completas);

        miprodutos_cadastrados.setText("Produto Cadastrados");
        miprodutos_cadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miprodutos_cadastradosActionPerformed(evt);
            }
        });
        mirelatorios.add(miprodutos_cadastrados);

        jMenuBar1.add(mirelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
          tempo.le_hora();
          lhora.setText(tempo.hora);
     }//GEN-LAST:event_timer1OnTime

     private void mipessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mipessoaActionPerformed
          new JFGerenciaPessoa(cx).setVisible(true);
     }//GEN-LAST:event_mipessoaActionPerformed

     private void mitipopessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitipopessoaActionPerformed
          new JFTipoPessoa(cx).setVisible(true);
     }//GEN-LAST:event_mitipopessoaActionPerformed

     private void migerenciaprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_migerenciaprodutoActionPerformed
          new JFGerenciaProduto(cx).setVisible(true);
     }//GEN-LAST:event_migerenciaprodutoActionPerformed

     private void micatprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micatprodutoActionPerformed
          new JFCategoriaProduto(cx).setVisible(true);
     }//GEN-LAST:event_micatprodutoActionPerformed

     private void miformapagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miformapagamentoActionPerformed
          new JFFormaPagamento(cx).setVisible(true);
     }//GEN-LAST:event_miformapagamentoActionPerformed

     private void misairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misairActionPerformed
          this.dispose();
     }//GEN-LAST:event_misairActionPerformed

     private void micompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micompraActionPerformed
          new JFComprar(cx).setVisible(true);
     }//GEN-LAST:event_micompraActionPerformed

     private void mivendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivendaActionPerformed
          new JFVenda(cx).setVisible(true); 
     }//GEN-LAST:event_mivendaActionPerformed

     private void mipaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mipaisActionPerformed
          new JFPais(cx).setVisible(true);
     }//GEN-LAST:event_mipaisActionPerformed

     private void miestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miestadoActionPerformed
          new JFEstado(cx).setVisible(true);
     }//GEN-LAST:event_miestadoActionPerformed

     private void miregiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miregiaoActionPerformed
          new JFRegiao(cx).setVisible(true);
     }//GEN-LAST:event_miregiaoActionPerformed

     private void micontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_micontaActionPerformed
          new JFConta(cx).setVisible(true);
     }//GEN-LAST:event_micontaActionPerformed

     private void mipaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mipaginaActionPerformed
          new JFPagina(cx).setVisible(true);
     }//GEN-LAST:event_mipaginaActionPerformed

     private void mivendas_incompletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivendas_incompletasActionPerformed
        try {
            InputStream is = Relatorio.lerArquivoNet("/src/relatorios/RelatorioVendasIncompletas.jasper");
            if(is != null){
                Map          parametros  = new HashMap();  
                cx.conectar();
                Connection   con         = cx.s.connection();
                Relatorio.openReport(con, "Lista de Vendas", parametros, is);
                cx.desconectar();
            }else{
                JOptionPane.showMessageDialog(null, "Arquivo de relatório não encontrado");
            }
          } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
          }    
     }//GEN-LAST:event_mivendas_incompletasActionPerformed

     private void mivendas_completasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivendas_completasActionPerformed
        try {
            InputStream is = Relatorio.lerArquivoNet("/src/relatorios/RelatorioVendasCompletas.jasper");
            if(is != null){
                Map          parametros  = new HashMap();  
                cx.conectar();
                Connection   con         = cx.s.connection();
                Relatorio.openReport(con, "Lista de Vendas", parametros, is);
                cx.desconectar();
            }else{
                JOptionPane.showMessageDialog(null, "Arquivo de relatório não encontrado");
            }
          } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
          }
     }//GEN-LAST:event_mivendas_completasActionPerformed

     private void miprodutos_cadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miprodutos_cadastradosActionPerformed
        try {
            InputStream is = Relatorio.lerArquivoNet("/src/relatorios/RelatorioProdutos.jasper");
            if(is != null){
                Map          parametros  = new HashMap();  
                cx.conectar();
                Connection   con         = cx.s.connection();
                Relatorio.openReport(con, "Lista de Vendas", parametros, is);
                cx.desconectar();
            }else{
                JOptionPane.showMessageDialog(null, "Arquivo de relatório não encontrado");
            }
          } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
          }
     }//GEN-LAST:event_miprodutos_cadastradosActionPerformed

     private void lcompra2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcompra2MouseClicked
          if(evt.getClickCount() == 1){
               new JFComprar(cx).setVisible(true);          
          }
     }//GEN-LAST:event_lcompra2MouseClicked

     private void lcompra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcompra1MouseClicked
          if(evt.getClickCount() == 1){
               new JFComprar(cx).setVisible(true);
          }
     }//GEN-LAST:event_lcompra1MouseClicked

     private void lvenda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvenda1MouseClicked
          if(evt.getClickCount() == 1){
               new JFVenda(cx).setVisible(true);
          }
     }//GEN-LAST:event_lvenda1MouseClicked

     private void lvenda2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvenda2MouseClicked
          if(evt.getClickCount() == 1){
               new JFVenda(cx).setVisible(true);
          }
     }//GEN-LAST:event_lvenda2MouseClicked

     private void lconta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lconta1MouseClicked
          if(evt.getClickCount() == 1){
               new JFConta(cx).setVisible(true);    
          }
     }//GEN-LAST:event_lconta1MouseClicked

     private void lpessoa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpessoa1MouseClicked
          if(evt.getClickCount() == 1){
               new JFGerenciaPessoa(cx).setVisible(true);
          }
     }//GEN-LAST:event_lpessoa1MouseClicked

     private void ltipopessoa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltipopessoa1MouseClicked
          if(evt.getClickCount() == 1){
               new JFTipoPessoa(cx).setVisible(true);
          }
     }//GEN-LAST:event_ltipopessoa1MouseClicked

     private void lconta2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lconta2MouseClicked
          if(evt.getClickCount() == 1){
               new JFConta(cx).setVisible(true);  
          }
     }//GEN-LAST:event_lconta2MouseClicked

     private void lrelatorio_venda1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrelatorio_venda1MouseClicked
          if(evt.getClickCount() == 1){
               try {
                 InputStream is = Relatorio.lerArquivoNet("/src/relatorios/RelatorioVendasCompletas.jasper");
                 if(is != null){
                     Map          parametros  = new HashMap();  
                     cx.conectar();
                     Connection   con         = cx.s.connection();
                     Relatorio.openReport(con, "Lista de Vendas", parametros, is);
                     cx.desconectar();
                 }else{
                     JOptionPane.showMessageDialog(null, "Arquivo de relatório não encontrado");
                 }
               } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
               }  
          }
     }//GEN-LAST:event_lrelatorio_venda1MouseClicked

     private void lrelatorio_venda2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrelatorio_venda2MouseClicked
          if(evt.getClickCount() == 1){
               try {
                 InputStream is = Relatorio.lerArquivoNet("/src/relatorios/RelatorioVendasIncompletas.jasper");
                 if(is != null){
                     Map          parametros  = new HashMap();  
                     cx.conectar();
                     Connection   con         = cx.s.connection();
                     Relatorio.openReport(con, "Lista de Vendas", parametros, is);
                     cx.desconectar();
                 }else{
                     JOptionPane.showMessageDialog(null, "Arquivo de relatório não encontrado");
                 }
               } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
               }
          }
     }//GEN-LAST:event_lrelatorio_venda2MouseClicked

     private void lrelatorio_produtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrelatorio_produtoMouseClicked
          if(evt.getClickCount() == 1){
               try {
                 InputStream is = Relatorio.lerArquivoNet("/src/relatorios/RelatorioProdutos.jasper");
                 if(is != null){
                     Map          parametros  = new HashMap();  
                     cx.conectar();
                     Connection   con         = cx.s.connection();
                     Relatorio.openReport(con, "Lista de Vendas", parametros, is);
                     cx.desconectar();
                 }else{
                     JOptionPane.showMessageDialog(null, "Arquivo de relatório não encontrado");
                 }
               } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
               }
          }
     }//GEN-LAST:event_lrelatorio_produtoMouseClicked

     private void labelsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelsMouseMoved
          MouseMao();
     }//GEN-LAST:event_labelsMouseMoved

     private void dpprincipalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpprincipalMouseMoved
          this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));    
     }//GEN-LAST:event_dpprincipalMouseMoved

     private void miavancadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miavancadasActionPerformed
          new JFAvancadas(cx).setVisible(true);
     }//GEN-LAST:event_miavancadasActionPerformed

     private void lrelatorio_contapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrelatorio_contapMouseClicked
          if(evt.getClickCount() == 1){
               try {
                 InputStream is = Relatorio.lerArquivoNet("/src/relatorios/RelatorioConta.jasper");
                 if(is != null){
                     Map          parametros  = new HashMap();  
                     cx.conectar();
                     Connection   con         = cx.s.connection();
                     Relatorio.openReport(con, "Lista de Contas", parametros, is);
                     cx.desconectar();
                 }else{
                     JOptionPane.showMessageDialog(null, "Arquivo de relatório não encontrado");
                 }
               } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
               }
          }
     }//GEN-LAST:event_lrelatorio_contapMouseClicked

     private void lrelatorio_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lrelatorio_clienteMouseClicked
          if(evt.getClickCount() == 1){
               try {
                 InputStream is = Relatorio.lerArquivoNet("/src/relatorios/RelatorioCliente.jasper");
                 if(is != null){
                     Map          parametros  = new HashMap();  
                     cx.conectar();
                     Connection   con         = cx.s.connection();
                     Relatorio.openReport(con, "Lista de Contas", parametros, is);
                     cx.desconectar();
                 }else{
                     JOptionPane.showMessageDialog(null, "Arquivo de relatório não encontrado");
                 }
               } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
               }
          }
     }//GEN-LAST:event_lrelatorio_clienteMouseClicked

     private void mivariacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mivariacaoActionPerformed
          new JFVariacao(cx).setVisible(true);
     }//GEN-LAST:event_mivariacaoActionPerformed

     private void lvariacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvariacaoMouseClicked
          if(evt.getClickCount() == 1){
               new JFVariacao(cx).setVisible(true);
          }
     }//GEN-LAST:event_lvariacaoMouseClicked

     private void lcategoriaprodutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcategoriaprodutoMouseClicked
          if(evt.getClickCount() == 1){
               new JFCategoriaProduto(cx).setVisible(true);
          }
     }//GEN-LAST:event_lcategoriaprodutoMouseClicked

     private void lproduto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lproduto1MouseClicked
          if(evt.getClickCount() == 1){
               new JFGerenciaProduto(cx).setVisible(true);
          }
     }//GEN-LAST:event_lproduto1MouseClicked

     private void lvendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvendedorMouseClicked
          if(evt.getClickCount() == 1){
               new JFGerenciaVendedor(cx).setVisible(true);
          }
     }//GEN-LAST:event_lvendedorMouseClicked

     private void lusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lusuarioMouseClicked
          if(evt.getClickCount() == 1){
               new JFGerenciaUsuario(cx).setVisible(true);
          }
     }//GEN-LAST:event_lusuarioMouseClicked

     private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          new JFGerenciaVendedor(cx).setVisible(true);
     }//GEN-LAST:event_jMenuItem1ActionPerformed

     private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          new JFGerenciaUsuario(cx).setVisible(true);
     }//GEN-LAST:event_jMenuItem2ActionPerformed

     private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
               jfvenda = new JFVenda(cx, usuario);
               centralizaJanela(jfvenda);
               jfvenda.setVisible(true);
     }//GEN-LAST:event_formWindowOpened

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if(evt.getClickCount() == 1){
            new JFGerenciaPessoa(cx).setVisible(true);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void ltipopessoa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltipopessoa2MouseClicked
        if(evt.getClickCount() == 1){
            new JFTipoPessoa(cx).setVisible(true);
        }
    }//GEN-LAST:event_ltipopessoa2MouseClicked
    
     
     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFPrincipal().setVisible(true);
               }
          });
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu jmsite;
    private javax.swing.JLabel lcategoriaproduto;
    private javax.swing.JLabel lcompra1;
    private javax.swing.JLabel lcompra2;
    private javax.swing.JLabel lconta;
    private javax.swing.JLabel lconta1;
    private javax.swing.JLabel lconta2;
    private javax.swing.JLabel ldata;
    private javax.swing.JLabel lestado;
    private javax.swing.JLabel lfinanceiro_logo;
    private javax.swing.JLabel lfuncionario;
    private javax.swing.JLabel lhora;
    private javax.swing.JLabel lpessoa1;
    private javax.swing.JLabel lpessoa_logo;
    private javax.swing.JLabel lproduto1;
    private javax.swing.JLabel lproduto_logo;
    private javax.swing.JLabel lrelatorio_cliente;
    private javax.swing.JLabel lrelatorio_contap;
    private javax.swing.JLabel lrelatorio_logo;
    private javax.swing.JLabel lrelatorio_produto;
    private javax.swing.JLabel lrelatorio_venda1;
    private javax.swing.JLabel lrelatorio_venda2;
    private javax.swing.JLabel lrelatorios;
    private javax.swing.JLabel ltipopessoa1;
    private javax.swing.JLabel ltipopessoa2;
    private javax.swing.JLabel lusuario;
    private javax.swing.JLabel lvariacao;
    private javax.swing.JLabel lvenda1;
    private javax.swing.JLabel lvenda2;
    private javax.swing.JLabel lvendas;
    private javax.swing.JLabel lvendasicompletas;
    private javax.swing.JLabel lvendedor;
    private javax.swing.JMenuItem miavancadas;
    private javax.swing.JMenuItem micatproduto;
    private javax.swing.JMenuItem micompra;
    private javax.swing.JMenuItem miconta;
    private javax.swing.JMenuItem miestado;
    private javax.swing.JMenuItem miformapagamento;
    private javax.swing.JMenuItem migerenciaproduto;
    private javax.swing.JMenuItem mipagina;
    private javax.swing.JMenuItem mipais;
    private javax.swing.JMenuItem mipessoa;
    private javax.swing.JMenuItem miprodutos_cadastrados;
    private javax.swing.JMenuItem miregiao;
    private javax.swing.JMenu mirelatorios;
    private javax.swing.JMenuItem misair;
    private javax.swing.JMenuItem mitipopessoa;
    private javax.swing.JMenuItem mivariacao;
    private javax.swing.JMenuItem mivenda;
    private javax.swing.JMenuItem mivendas_completas;
    private javax.swing.JMenuItem mivendas_incompletas;
    private javax.swing.JPanel pfinanceiro;
    private javax.swing.JPanel pinformacoes_financeiras;
    private javax.swing.JPanel pinformacoes_sistema;
    private javax.swing.JPanel ppessoa;
    private javax.swing.JPanel pproduto;
    private javax.swing.JPanel prelatorio;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables

     public final void conectar(){
          try{
               lestado.setText("Conectado");
               lfuncionario.setText("Bem vindo usuário:" + usuario.getPrimeironome().toUpperCase() + " " + usuario.getUltimonome().toUpperCase());
               procuraContasAPagar();
               procuraVendasCompletas();
               procuraVendasIncompletas();
          }catch(Exception ex){
               JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex + "\nContate a empresa de desenvolvimento em:\n"
               + "contato@megacia.com.br");
          }
     }
     
     public void procuraContasAPagar(){
          double         total     = 0;
          ContaRN        crn       = new ContaRN();
          List<Conta>    obj       = crn.procuraEstado(cx, "Não-Pago"); 
          if(obj != null && !obj.isEmpty()){
               for (Conta ct : obj) {
                    total    = ct.getValor() + total;
               }
               lconta.setText(Mascara.formatMoeda(total));
          }else{
               lvendas.setText("0");
          }        
     }
     
     public void procuraVendasCompletas(){
          List<Venda> obj = vrn.procuraEstado(cx, "Completo");
          iteraVenda(lvendas, obj);
     }
     
     public void procuraVendasIncompletas(){
          List<Venda> obj = vrn.procuraVendasIncompletas(cx);
          iteraVenda(lvendasicompletas, obj);     
     }
     
     public void iteraVenda(JLabel label, List<Venda> obj){
          double total = 0;
          if(obj != null && !obj.isEmpty()){
               for (Venda v : obj) {
                    total   = v.getValor() + total;
               }
               label.setText("Ganho:" + Mascara.formatMoeda(total) + ", Qtd. Vendas:" + obj.size());
          }else{
               label.setText("0");
          }          
     }

     /**Para centralizar Janela
      @param jf manda o componente ao qual deseja centralizar
      **/
     private void centralizaJanela(JFrame jf) {
          jf.setLocation((int) (screenWidth / 4), (int) (screenHeight / 10));   
     }

     private void MouseMao(){
          this.setCursor(new Cursor(Cursor.HAND_CURSOR));            
     }
}
