/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.TipoPessoaRN;
import persistencia.Conexao;
import recursos.utilitarios.TableModel;
import vo.TipoPessoa;

/**
 *
 * @author ThyagoHenrique
 */
public class JFTipoPessoa extends javax.swing.JFrame {
     String              titulo[]            = new String[]{"Código", "Nome"};
     TableModel          tm                  = new TableModel(titulo, 1, titulo.length);         
     List<TipoPessoa>    obj                 = new ArrayList();
     TipoPessoa          tipo                = new TipoPessoa();
     TipoPessoaRN        trn                 = new TipoPessoaRN();
     Conexao             cx;
     /**
      * Creates new form JFTipoPessoa
      */
     public JFTipoPessoa() {
          initComponents();
     }

     public JFTipoPessoa(Conexao cx) {
          initComponents();
          this.cx = cx;
          tabela.setModel(tm);
     }          
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTabbedPane1 = new javax.swing.JTabbedPane();
          jPanel1 = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          tnome = new javax.swing.JTextField();
          bsair = new javax.swing.JButton();
          bexcluir = new javax.swing.JButton();
          bupdate = new javax.swing.JButton();
          binserir = new javax.swing.JButton();
          jPanel2 = new javax.swing.JPanel();
          jLabel2 = new javax.swing.JLabel();
          tnomeproc = new javax.swing.JTextField();
          bprocurar = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          tabela = new javax.swing.JTable();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Tipos de Pessoa");

          jLabel1.setText("Nome");

          bsair.setText("Sair");
          bsair.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bsairActionPerformed(evt);
               }
          });

          bexcluir.setText("Excluir");
          bexcluir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluirActionPerformed(evt);
               }
          });

          bupdate.setText("update");
          bupdate.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bupdateActionPerformed(evt);
               }
          });

          binserir.setText("Inserir");
          binserir.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserirActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(binserir)
                    .addGap(18, 18, 18)
                    .addComponent(bupdate)
                    .addGap(18, 18, 18)
                    .addComponent(bexcluir)
                    .addGap(18, 18, 18)
                    .addComponent(bsair)
                    .addGap(32, 32, 32))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(65, 65, 65)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bsair)
                         .addComponent(bexcluir)
                         .addComponent(bupdate)
                         .addComponent(binserir))
                    .addContainerGap(145, Short.MAX_VALUE))
          );

          jTabbedPane1.addTab("Cadastro", jPanel1);

          jLabel2.setText("Nome");

          bprocurar.setText("Procurar");
          bprocurar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bprocurarActionPerformed(evt);
               }
          });

          tabela.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null},
                    {null, null},
                    {null, null},
                    {null, null}
               },
               new String [] {
                    "Código", "Nome"
               }
          ));
          tabela.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabelaMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tabela);

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                         .addGroup(jPanel2Layout.createSequentialGroup()
                              .addComponent(jLabel2)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(bprocurar)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(tnomeproc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(bprocurar))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addContainerGap())
          );

          jTabbedPane1.addTab("Procurar", jPanel2);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane1)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane1)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void bsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsairActionPerformed
          this.dispose();
     }//GEN-LAST:event_bsairActionPerformed

     private void bexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluirActionPerformed
          String msg      = "";
          int    response = JOptionPane.showConfirmDialog(null, "Tem certeza disso,\n"
               + "Você quer excluir?", "Confirmação de excluir:",
               JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if (response == JOptionPane.YES_OPTION) {
               if(tipo != null && tipo.getCodigo() != null){
                    msg = trn.excluirTipoPessoa(cx, tipo);
               }else{
                    JOptionPane.showMessageDialog(null, "Para excluir escolha antes uma tipo que tenha sido gravada no banco");
               }
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.remove(tipo);
               listar();
               JOptionPane.showMessageDialog(null, "Excluido com sucesso");
          }
     }//GEN-LAST:event_bexcluirActionPerformed

     private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
          tipo.setNome(tnome.getText());
          String msg = trn.updateTipoPessoa(cx, tipo);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               for(int i = 0; i < obj.size(); i++){
                    if(obj.get(i).getCodigo() == tipo.getCodigo()){
                         obj.set(i, tipo);
                         listar();
                         break;
                    }
               }
               JOptionPane.showMessageDialog(null, "Atualizado com sucesso");
          }
     }//GEN-LAST:event_bupdateActionPerformed

     private void binserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserirActionPerformed
          tipo = new TipoPessoa();
          tipo.setNome(tnome.getText().toUpperCase());
          String msg = trn.inserirTipoPessoa(cx, tipo);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj.add(tipo);
               listar();
               JOptionPane.showMessageDialog(null, "Inserido com sucesso");
          }
     }//GEN-LAST:event_binserirActionPerformed

     private void bprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprocurarActionPerformed
          obj = trn.procuraNomeParcial(cx, tnomeproc.getText());
          if(obj != null && !obj.isEmpty()){
               listar();
          }else{
               JOptionPane.showMessageDialog(null, "Nada encontrado");
          }
     }//GEN-LAST:event_bprocurarActionPerformed

     private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
          tipo = obj.get(tabela.getSelectedRow());
          tnome.setText(tipo.getNome().toUpperCase());
     }//GEN-LAST:event_tabelaMouseClicked

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (ClassNotFoundException ex) {
               java.util.logging.Logger.getLogger(JFTipoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
               java.util.logging.Logger.getLogger(JFTipoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
               java.util.logging.Logger.getLogger(JFTipoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
               java.util.logging.Logger.getLogger(JFTipoPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFTipoPessoa().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton bupdate;
     private javax.swing.JButton bexcluir;
     private javax.swing.JButton binserir;
     private javax.swing.JButton bprocurar;
     private javax.swing.JButton bsair;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JTable tabela;
     private javax.swing.JTextField tnome;
     private javax.swing.JTextField tnomeproc;
     // End of variables declaration//GEN-END:variables

   /**lista tudo o que está na tabela**/  
    private void listar() {
            tabela.setModel(new TableModel(titulo, obj.size(), titulo.length));
            for(int i=0; i < obj.size(); i++){
                    tabela.setValueAt(obj.get(i).getCodigo(), i, 0);
                    tabela.setValueAt(obj.get(i).getNome().toUpperCase(), i, 1);
            }
            tabela.setAutoCreateRowSorter(true);    
    }  
}
