/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import negocio.ItemVariacaoRN;
import negocio.VariacaoRN;
import persistencia.Conexao;
import recursos.utilitarios.TableModel;
import vo.ItemVariacao;
import vo.Variacao;

/**
 *
 * @author ThyagoHenrique
 */
public class JFVariacao extends javax.swing.JFrame {

     Conexao             cx;
     String              titulo_variacao[]        = new String[]{"Código", "Nome"};
     TableModel          tm_variacao              = new TableModel(titulo_variacao, 1, titulo_variacao.length);  
     String              titulo_ivariacao[]       = new String[]{"Código", "Nome", "Valor"};
     TableModel          tm_ivariacao             = new TableModel(titulo_ivariacao, 1, titulo_ivariacao.length);      
     ItemVariacaoRN      ivrn                     = new ItemVariacaoRN();
     VariacaoRN          vrn                      = new VariacaoRN();
     Variacao            variacao                 = new Variacao();
     ItemVariacao        ivariacao                = new ItemVariacao();
     List<ItemVariacao>  obj_ivariacao            = new ArrayList();
     List<Variacao>      obj_variacao             = new ArrayList();
     
     /**
      * Creates new form JFVariacao
      */
     public JFVariacao() {
          initComponents();
     }

     public JFVariacao(Conexao cx) {
          initComponents();
          this.cx = cx;
          tabela_variacao.setModel(tm_variacao);
          tabela_ivariacao.setModel(tm_ivariacao);
     }          
     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTabbedPane1 = new javax.swing.JTabbedPane();
          jPanel1 = new javax.swing.JPanel();
          jLabel2 = new javax.swing.JLabel();
          titem = new javax.swing.JTextField();
          tnome = new javax.swing.JTextField();
          jLabel1 = new javax.swing.JLabel();
          bsair = new javax.swing.JButton();
          bexcluir_variacao = new javax.swing.JButton();
          bupdate_variacao = new javax.swing.JButton();
          binserir_variacao = new javax.swing.JButton();
          binserir_item_variacao = new javax.swing.JButton();
          tvalor = new javax.swing.JTextField();
          jLabel5 = new javax.swing.JLabel();
          jPanel3 = new javax.swing.JPanel();
          jScrollPane2 = new javax.swing.JScrollPane();
          tabela_ivariacao = new javax.swing.JTable();
          bexcluir_ivariacao = new javax.swing.JButton();
          tnome_ivariacao = new javax.swing.JTextField();
          jLabel4 = new javax.swing.JLabel();
          bprocurar_ivariacao = new javax.swing.JButton();
          jPanel2 = new javax.swing.JPanel();
          jLabel3 = new javax.swing.JLabel();
          tnome_variacao = new javax.swing.JTextField();
          bprocurar_variacao = new javax.swing.JButton();
          jScrollPane1 = new javax.swing.JScrollPane();
          tabela_variacao = new javax.swing.JTable();

          setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
          setTitle("Variações de produto");

          jLabel2.setText("Item");

          jLabel1.setText("Nome");

          bsair.setText("Sair");
          bsair.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bsairActionPerformed(evt);
               }
          });

          bexcluir_variacao.setText("Excluir");
          bexcluir_variacao.setToolTipText("Excluir variação");
          bexcluir_variacao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluir_variacaoActionPerformed(evt);
               }
          });

          bupdate_variacao.setText("update");
          bupdate_variacao.setToolTipText("update variação");
          bupdate_variacao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bupdate_variacaoActionPerformed(evt);
               }
          });

          binserir_variacao.setText("Inserir");
          binserir_variacao.setToolTipText("Inserir variação");
          binserir_variacao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserir_variacaoActionPerformed(evt);
               }
          });

          binserir_item_variacao.setText("Inserir");
          binserir_item_variacao.setToolTipText("Inserir item variação");
          binserir_item_variacao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    binserir_item_variacaoActionPerformed(evt);
               }
          });

          jLabel5.setText("Valor");

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel5))
                              .addGap(0, 18, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(titem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(binserir_variacao)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(bupdate_variacao)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(bexcluir_variacao)
                              .addGap(18, 18, 18)
                              .addComponent(bsair))
                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                   .addComponent(tvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(binserir_item_variacao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(28, Short.MAX_VALUE))
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(tnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bexcluir_variacao)
                         .addComponent(bupdate_variacao)
                         .addComponent(binserir_variacao)
                         .addComponent(bsair))
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(titem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(tvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel5)
                         .addComponent(binserir_item_variacao))
                    .addContainerGap(93, Short.MAX_VALUE))
          );

          jTabbedPane1.addTab("Cadastro", jPanel1);

          tabela_ivariacao.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          tabela_ivariacao.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabela_ivariacaoMouseClicked(evt);
               }
          });
          jScrollPane2.setViewportView(tabela_ivariacao);

          bexcluir_ivariacao.setText("Excluir");
          bexcluir_ivariacao.setToolTipText("Excluir item variação");
          bexcluir_ivariacao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bexcluir_ivariacaoActionPerformed(evt);
               }
          });

          jLabel4.setText("Nome");

          bprocurar_ivariacao.setText("Procurar");
          bprocurar_ivariacao.setToolTipText("Procura em todas as variações por item de variação");
          bprocurar_ivariacao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bprocurar_ivariacaoActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
          jPanel3.setLayout(jPanel3Layout);
          jPanel3Layout.setHorizontalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tnome_ivariacao, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(bprocurar_ivariacao)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bexcluir_ivariacao)
                    .addGap(19, 19, 19))
               .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          );
          jPanel3Layout.setVerticalGroup(
               jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(bexcluir_ivariacao)
                         .addComponent(tnome_ivariacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel4)
                         .addComponent(bprocurar_ivariacao))
                    .addContainerGap(238, Short.MAX_VALUE))
               .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                         .addContainerGap(27, Short.MAX_VALUE)
                         .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap()))
          );

          jTabbedPane1.addTab("Item Variação", jPanel3);

          jLabel3.setText("Nome");

          bprocurar_variacao.setText("Procurar");
          bprocurar_variacao.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bprocurar_variacaoActionPerformed(evt);
               }
          });

          tabela_variacao.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
               },
               new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
               }
          ));
          tabela_variacao.addMouseListener(new java.awt.event.MouseAdapter() {
               public void mouseClicked(java.awt.event.MouseEvent evt) {
                    tabela_variacaoMouseClicked(evt);
               }
          });
          jScrollPane1.setViewportView(tabela_variacao);

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tnome_variacao, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(bprocurar_variacao)
                    .addGap(32, 32, 32))
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                         .addContainerGap(18, Short.MAX_VALUE)
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap(18, Short.MAX_VALUE)))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel3)
                         .addComponent(tnome_variacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(bprocurar_variacao))
                    .addContainerGap(238, Short.MAX_VALUE))
               .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                         .addContainerGap(38, Short.MAX_VALUE)
                         .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addContainerGap()))
          );

          jTabbedPane1.addTab("Procurar", jPanel2);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane1)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jTabbedPane1)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void bsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsairActionPerformed
          dispose();
     }//GEN-LAST:event_bsairActionPerformed

     private void bexcluir_variacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluir_variacaoActionPerformed
          String msg = vrn.excluirVariacao(cx, variacao);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               for(int i = 0; i < obj_variacao.size(); i++){
                    if(obj_variacao.get(i).getCodigo() == variacao.getCodigo()){
                         obj_variacao.remove(i);
                         listar_variacao();
                         break;
                    }
               }
               JOptionPane.showMessageDialog(null, "Excluido com sucesso");
          }
     }//GEN-LAST:event_bexcluir_variacaoActionPerformed

     private void bupdate_variacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdate_variacaoActionPerformed
          setaVariacao();
          String msg = vrn.updateVariacao(cx, variacao);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               for(int i = 0; i < obj_variacao.size(); i++){
                    if(obj_variacao.get(i).getCodigo() == variacao.getCodigo()){
                         obj_variacao.set(i, variacao);
                         listar_variacao();
                         break;
                    }
               }
               JOptionPane.showMessageDialog(null, "Atualizado com sucesso");
          }
     }//GEN-LAST:event_bupdate_variacaoActionPerformed

     private void binserir_variacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserir_variacaoActionPerformed
          variacao = new Variacao();
          setaVariacao();
          String msg = vrn.inserirVariacao(cx, variacao);
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj_variacao.add(variacao);
               listar_variacao();
               JOptionPane.showMessageDialog(null, "Inserido com sucesso");
          }
     }//GEN-LAST:event_binserir_variacaoActionPerformed

     private void binserir_item_variacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binserir_item_variacaoActionPerformed
          String msg;
          if(variacao != null && variacao.getCodigo() != null){
               ivariacao = new ItemVariacao();
               setaIVariacao();
               msg = ivrn.inserirItemVariacao(cx, ivariacao);
          }else{
               msg = "Precisa confirmar o nome de uma variação antes";
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               obj_ivariacao.add(ivariacao);
               listar_ivariacao();
               JOptionPane.showMessageDialog(null, "Inserido com sucesso");
          }
     }//GEN-LAST:event_binserir_item_variacaoActionPerformed

     private void tabela_ivariacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_ivariacaoMouseClicked
          ivariacao = obj_ivariacao.get(tabela_ivariacao.getSelectedRow());
          if(ivariacao != null && ivariacao.getCodigo() != null){
               setaTelaIVariacao();
          }
     }//GEN-LAST:event_tabela_ivariacaoMouseClicked

     private void bexcluir_ivariacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexcluir_ivariacaoActionPerformed
          String msg;
          if(variacao != null && variacao.getCodigo() != null){
               setaIVariacao();
               msg = ivrn.excluirItemVariacao(cx, ivariacao);
          }else{
               msg = "Precisa confirmar o nome de uma variação antes";
          }
          if(msg != null && !msg.isEmpty()){
               JOptionPane.showMessageDialog(null, msg);
          }else{
               for(int i = 0; i < obj_ivariacao.size(); i++){
                    if(obj_ivariacao.get(i).getCodigo() == ivariacao.getCodigo()){
                         obj_ivariacao.remove(i);
                         listar_ivariacao();
                         break;
                    }
               }
               JOptionPane.showMessageDialog(null, "Inserido com sucesso");
          }
     }//GEN-LAST:event_bexcluir_ivariacaoActionPerformed

     private void bprocurar_ivariacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprocurar_ivariacaoActionPerformed
          obj_ivariacao = ivrn.procuraNomeParcial(cx, tnome_ivariacao.getText());
          if(obj_ivariacao != null && !obj_ivariacao.isEmpty()){
               listar_ivariacao();
          }else{
               JOptionPane.showMessageDialog(null, "Nada encontrado");
          }
     }//GEN-LAST:event_bprocurar_ivariacaoActionPerformed

     private void bprocurar_variacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprocurar_variacaoActionPerformed
          obj_variacao = vrn.procuraNomeParcial(cx, tnome_variacao.getText());
          if(obj_variacao != null && !obj_variacao.isEmpty()){
               listar_variacao();
          }else{
               JOptionPane.showMessageDialog(null, "Nada encontrado");
          }
     }//GEN-LAST:event_bprocurar_variacaoActionPerformed

     private void tabela_variacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_variacaoMouseClicked
          if(obj_variacao != null && !obj_variacao.isEmpty()){
               variacao = obj_variacao.get(tabela_variacao.getSelectedRow());
               setaTelaVariacao();
          }
     }//GEN-LAST:event_tabela_variacaoMouseClicked

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
           * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
               for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                         javax.swing.UIManager.setLookAndFeel(info.getClassName());
                         break;
                    }
               }
          } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, "Erro causado por:\n" + ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
               @Override
               public void run() {
                    new JFVariacao().setVisible(true);
               }
          });
     }
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton bupdate_variacao;
     private javax.swing.JButton bexcluir_ivariacao;
     private javax.swing.JButton bexcluir_variacao;
     private javax.swing.JButton binserir_item_variacao;
     private javax.swing.JButton binserir_variacao;
     private javax.swing.JButton bprocurar_ivariacao;
     private javax.swing.JButton bprocurar_variacao;
     private javax.swing.JButton bsair;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanel3;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JTable tabela_ivariacao;
     private javax.swing.JTable tabela_variacao;
     private javax.swing.JTextField titem;
     private javax.swing.JTextField tnome;
     private javax.swing.JTextField tnome_ivariacao;
     private javax.swing.JTextField tnome_variacao;
     private javax.swing.JTextField tvalor;
     // End of variables declaration//GEN-END:variables
     private void listar_variacao() {
            tabela_variacao.setModel(new TableModel(titulo_variacao, obj_variacao.size(), titulo_variacao.length));
            for(int i = 0; i < obj_variacao.size(); i++){
                    tabela_variacao.setValueAt(obj_variacao.get(i).getCodigo(), i, 0);
                    tabela_variacao.setValueAt(obj_variacao.get(i).getNome(), i, 1);
            }
            tabela_variacao.setAutoCreateRowSorter(true); 
     }

     private void listar_ivariacao() {
            tabela_ivariacao.setModel(new TableModel(titulo_ivariacao, obj_ivariacao.size(), titulo_ivariacao.length));
            for(int i = 0; i < obj_ivariacao.size(); i++){
                    tabela_ivariacao.setValueAt(obj_ivariacao.get(i).getCodigo(), i, 0);
                    tabela_ivariacao.setValueAt(obj_ivariacao.get(i).getNome(), i, 1);
                    tabela_ivariacao.setValueAt(obj_ivariacao.get(i).getValor(), i, 2);
            }
            tabela_ivariacao.setAutoCreateRowSorter(true); 
     }

     private void setaVariacao() {
          variacao.setNome(tnome.getText());
     }
     
     private void setaTelaVariacao(){
          tnome.setText(variacao.getNome());
          obj_ivariacao = ivrn.procuraVariacao(cx, variacao.getCodigo());
          if(obj_ivariacao != null && !obj_ivariacao.isEmpty()){
               listar_ivariacao();
          }
     }

     private void setaIVariacao() {
               ivariacao.setNome(titem.getText());
               ivariacao.setValor(tvalor.getText());
               ivariacao.setVariacao(variacao);
     }

     private void setaTelaIVariacao() {
          titem.setText(ivariacao.getNome());
          tvalor.setText(ivariacao.getValor());
          variacao = ivariacao.getVariacao();
          setaTelaVariacao();
     }
}
